import 'package:flutter/material.dart';
import '../../../core/design_system/design_system.dart';

String lt(BuildContext context, String key) => leaseText(key, context.isArabic);
String leaseInline(String value) => '\u2068$value\u2069';
String leaseDateLabel(BuildContext context, String value, {bool time = false}) {
  final date = DateTime.tryParse(value)?.toLocal();
  if (date == null) return value;
  final localizations = MaterialLocalizations.of(context);
  final day = localizations.formatMediumDate(date);
  return time
      ? '$day ${localizations.formatTimeOfDay(TimeOfDay.fromDateTime(date))}'
      : day;
}

String leaseText(String key, bool arabic) {
  final pair = leaseStrings[key];
  return pair == null ? key : pair[arabic ? 0 : 1];
}

const leaseStrings = <String, List<String>>{
  'contracts': ['عقود الإيجار', 'Lease contracts'],
  'tenants': ['المستأجرون', 'Tenants'],
  'filters': ['تصفية وترتيب', 'Filter and sort'],
  'done': ['تم', 'Done'],
  'results': ['النتائج', 'Results'],
  'identity': ['البيانات الأساسية', 'Identity'],
  'contact': ['معلومات التواصل', 'Contact information'],
  'employment': ['معلومات العمل', 'Employment'],
  'newTenant': ['إضافة مستأجر', 'Add tenant'],
  'editTenant': ['تعديل المستأجر', 'Edit tenant'],
  'tenantDetails': ['تفاصيل المستأجر', 'Tenant details'],
  'tenantSearch': [
    'البحث بالاسم أو الهوية أو الهاتف',
    'Search name, ID or phone',
  ],
  'tenantEmpty': ['لا يوجد مستأجرون', 'No tenants'],
  'tenantEmptyHint': [
    'لم يتم العثور على مستأجرين مطابقين.',
    'No matching tenants were found.',
  ],
  'name': ['الاسم', 'Name'],
  'nationalId': ['الرقم الوطني', 'National ID'],
  'phone': ['رقم الهاتف', 'Phone number'],
  'email': ['البريد الإلكتروني', 'Email address'],
  'occupation': ['المهنة', 'Occupation'],
  'employer': ['جهة العمل', 'Employer'],
  'tenantRequired': [
    'الاسم والهوية والهاتف والبريد مطلوبة.',
    'Name, ID, phone and email are required.',
  ],
  'deleteTenant': ['حذف المستأجر', 'Delete tenant'],
  'deleteTenantHint': [
    'سيتم حذف سجل المستأجر التالي:',
    'The following tenant record will be deleted:',
  ],
  'editRecord': ['تعديل', 'Edit'],
  'add': ['إضافة', 'Add'],
  'tenantActions': ['إجراءات المستأجر', 'Tenant actions'],
  'recordActions': ['إجراءات السجل', 'Record actions'],
  'provision': ['إنشاء حساب', 'Create account'],
  'provisionTenant': ['إنشاء حساب للمستأجر', 'Create tenant account'],
  'contactMethod': ['طريقة التواصل', 'Contact method'],
  'contactRequired': ['أدخل وسيلة التواصل.', 'Enter contact details.'],
  'accountCreated': ['تم إنشاء حساب المستأجر.', 'Tenant account created.'],
  'family': ['أفراد الأسرة', 'Family members'],
  'relationship': ['صلة القرابة', 'Relationship'],
  'ageBracket': ['الفئة العمرية (اختياري)', 'Age group (optional)'],
  'emergency': ['جهات اتصال الطوارئ', 'Emergency contacts'],
  'vehicles': ['المركبات', 'Vehicles'],
  'plate': ['رقم اللوحة', 'Plate number'],
  'makeModel': ['الصنع والموديل', 'Make and model'],
  'color': ['اللون', 'Color'],
  'tenantLeaseHistory': ['سجل عقود الإيجار', 'Lease history'],
  'tenantNoLeases': [
    'لا يوجد سجل عقود لهذا المستأجر.',
    'This tenant has no lease history.',
  ],
  'noRecords': ['لا توجد بيانات مسجلة.', 'No records yet.'],
  'requiredFields': ['أكمل الحقول المطلوبة.', 'Complete the required fields.'],
  'settlement': ['التسوية النهائية', 'Final settlement'],
  'emptyHint': [
    'جرّب تغيير البحث أو التبويب.',
    'Try changing the search or tab.',
  ],
  'clearSearch': ['مسح البحث', 'Clear search'],
  'leasing': ['التأجير', 'Leasing'],
  'all': ['جميع العقود', 'All contracts'],
  'expiring': ['تنتهي قريباً', 'Expiring'],
  'days': ['أيام', 'days'],
  'daysAhead': ['خلال', 'Within'],
  'search': ['بحث في النتائج المحمّلة', 'Search loaded results'],
  'window': [
    'تُعرض النتائج التي أعادها الخادم فقط (حتى 50 عقداً).',
    'Only the server-returned results are shown (up to 50 contracts).',
  ],
  'sort': ['الترتيب', 'Sort'],
  'none': ['ترتيب الخادم', 'Server order'],
  'ascending': ['تصاعدي', 'Ascending'],
  'descending': ['تنازلي', 'Descending'],
  'previous': ['السابق', 'Previous'],
  'next': ['التالي', 'Next'],
  'page': ['صفحة', 'Page'],
  'of': ['من', 'of'],
  'empty': ['لا توجد عقود', 'No contracts'],
  'emptySearch': ['لا توجد نتائج مطابقة', 'No matching results'],
  'retry': ['إعادة المحاولة', 'Retry'],
  'loading': ['جارٍ التحميل', 'Loading'],
  'failure': ['تعذر إكمال العملية', 'Unable to complete the action'],
  'view': ['عرض التفاصيل', 'View details'],
  'edit': ['تعديل المسودة', 'Edit draft'],
  'create': ['عقد جديد', 'New contract'],
  'activate': ['تفعيل العقد', 'Activate'],
  'renew': ['تجديد العقد', 'Renew'],
  'terminate': ['إنهاء العقد', 'Terminate'],
  'attach': ['إرفاق مستند', 'Attach document'],
  'cancel': ['إلغاء', 'Cancel'],
  'save': ['حفظ', 'Save'],
  'saved': ['تم الحفظ بنجاح', 'Saved successfully'],
  'actions': ['إجراءات العقد', 'Contract actions'],
  'contractNumber': ['رقم العقد', 'Contract number'],
  'status': ['الحالة', 'Status'],
  'startDate': ['تاريخ البداية', 'Start date'],
  'endDate': ['تاريخ النهاية', 'End date'],
  'monthlyRentAmount': ['الإيجار الشهري (JOD)', 'Monthly rent (JOD)'],
  'rent': ['الإيجار الشهري', 'Monthly rent'],
  'securityDepositAmount': ['مبلغ التأمين (JOD)', 'Security deposit (JOD)'],
  'deposit': ['التأمين', 'Security deposit'],
  'paymentFrequency': ['دورية الدفع', 'Payment frequency'],
  'paymentDueDay': ['يوم الاستحقاق (1–28)', 'Due day (1–28)'],
  'legalRegime': ['النظام القانوني', 'Legal regime'],
  'tenantType': ['نوع المستأجر', 'Tenant type'],
  'notes': ['ملاحظات', 'Notes'],
  'building': ['المبنى', 'Building'],
  'apartmentId': ['الوحدة', 'Apartment'],
  'tenantId': ['المستأجر', 'Tenant'],
  'choose': ['اختر', 'Select'],
  'buildingFirst': ['اختر المبنى أولاً', 'Select a building first'],
  'noApartments': [
    'لا توجد وحدات في هذا المبنى. لا يمكن إنشاء عقد دون وحدة.',
    'No apartments in this building. A lease requires an apartment.',
  ],
  'noTenants': [
    'لا يوجد مستأجرون متاحون. إدارة المستأجرين وحدة مستقلة.',
    'No tenants available. Tenant management is a separate module.',
  ],
  'suggestion': ['رقم مقترح قابل للتعديل', 'Suggested number; editable'],
  'rentDefault': [
    'تم اقتراح الإيجار من الوحدة ويمكن تعديله.',
    'Rent suggested from the apartment; editable.',
  ],
  'terms': ['شروط العقد', 'Contract terms'],
  'parties': ['العقار والمستأجر', 'Property and tenant'],
  'financial': ['الشروط المالية', 'Financial terms'],
  'required': ['هذا الحقل مطلوب.', 'This field is required.'],
  'positive': [
    'أدخل مبلغاً أكبر من صفر.',
    'Enter an amount greater than zero.',
  ],
  'nonnegative': [
    'أدخل مبلغاً يساوي صفراً أو أكبر.',
    'Enter a nonnegative amount.',
  ],
  'dueDay': [
    'أدخل يوماً صحيحاً بين 1 و28.',
    'Enter a whole day between 1 and 28.',
  ],
  'related': ['الروابط ذات الصلة', 'Related entities'],
  'parking': ['المواقف', 'Parking'],
  'noParking': [
    'لا توجد مواقف مخصصة لهذا العقد.',
    'No parking spots are assigned to this contract.',
  ],
  'viewApartment': ['عرض الوحدة', 'View apartment'],
  'viewTenants': ['عرض المستأجرين', 'View tenants'],
  'tenantDependency': [
    'سيتوفر هذا الرابط عند تنفيذ وحدة إدارة المستأجرين المستقلة.',
    'This destination will be available when the separate Tenants module is implemented.',
  ],
  'prior': ['العقد السابق', 'Prior contract'],
  'history': ['سجل الحالات', 'Status history'],
  'apartmentHistory': ['سجل عقود الوحدة', 'Apartment lease history'],
  'noHistory': ['لا يوجد سجل', 'No history'],
  'signed': ['تاريخ التوقيع', 'Signed date'],
  'termination': ['تفاصيل الإنهاء', 'Termination details'],
  'terminationType': ['نوع الإنهاء', 'Termination type'],
  'terminationDate': ['تاريخ الإنهاء', 'Termination date'],
  'outstandingBalance': ['الرصيد المستحق', 'Outstanding balance'],
  'depositReturnedAmount': ['التأمين المسترد', 'Deposit returned'],
  'depositDeductionAmount': ['المقتطع من التأمين', 'Deposit deduction'],
  'depositDeductionReason': ['سبب الاقتطاع', 'Deduction reason'],
  'finalUtilitySettlementCompleted': [
    'اكتملت تسوية المرافق النهائية',
    'Final utility settlement completed',
  ],
  'reason': ['السبب', 'Reason'],
  'yes': ['نعم', 'Yes'],
  'no': ['لا', 'No'],
  'activateConfirm': [
    'هل تريد تفعيل هذا العقد؟ يلزم مستند عقد موقّع وتبقى شروط الخادم مطبّقة.',
    'Activate this contract? A signed contract document is required; server rules still apply.',
  ],
  'terminateWarning': [
    'سيتم إنهاء العقد النشط باستخدام بيانات التسوية التالية.',
    'The active contract will be terminated using the following settlement details.',
  ],
  'documents': ['المستندات', 'Documents'],
  'noDocuments': ['لا توجد مستندات', 'No documents'],
  'file': ['الملف', 'File'],
  'selectFile': ['اختيار ملف', 'Select file'],
  'removeFile': ['إزالة الملف المختار', 'Remove selected file'],
  'documentType': ['نوع المستند', 'Document type'],
  'description': ['الوصف', 'Description'],
  'fileSupport': [
    'PDF، PNG، JPEG، DOC، DOCX — حتى 25 MB',
    'PDF, PNG, JPEG, DOC, DOCX — up to 25 MB',
  ],
  'fileTooLarge': ['حجم الملف يتجاوز 25 MB.', 'The file exceeds 25 MB.'],
  'fileType': ['نوع الملف غير مدعوم.', 'Unsupported file type.'],
  'uploading': ['جارٍ رفع الملف', 'Uploading file'],
  'preparing': ['جارٍ تجهيز الرفع', 'Preparing upload'],
  'confirming': ['جارٍ تأكيد الملف', 'Confirming file'],
  'attaching': ['جارٍ ربط المستند', 'Attaching document'],
  'viewDoc': ['عرض', 'View'],
  'download': ['تنزيل', 'Download'],
  'replace': ['استبدال', 'Replace'],
  'delete': ['حذف', 'Delete'],
  'deleteConfirm': ['هل تريد حذف هذا المستند؟', 'Delete this document?'],
  'documentSaved': ['تم تحديث المستندات', 'Documents updated'],
  'utilities': ['الكهرباء والمياه', 'Electricity and water'],
  'electricity': ['الكهرباء', 'Electricity'],
  'water': ['المياه', 'Water'],
  'link': ['ربط حساب', 'Link account'],
  'sync': ['مزامنة', 'Sync'],
  'unlink': ['إلغاء الربط', 'Unlink'],
  'number': ['رقم الاشتراك', 'Account number'],
  'meter': ['رقم العداد (اختياري)', 'Meter number (optional)'],
  'previousAccounts': ['الاشتراكات السابقة', 'Previous accounts'],
  'syncQueued': ['تم طلب المزامنة', 'Sync requested'],
  'unlinkConfirm': [
    'هل تريد إلغاء ربط الحساب؟ سيبقى سجل الفواتير محفوظاً.',
    'Unlink this account? Bill history remains preserved.',
  ],
  'utilityNumber': [
    'الكهرباء: 10 أرقام. المياه: من 1 إلى 20 رقماً.',
    'Electricity: 10 digits. Water: 1–20 digits.',
  ],
  'permission': [
    'ليس لديك صلاحية لهذا الإجراء.',
    'You do not have permission for this action.',
  ],
  'unknown': ['غير معروف', 'Unknown'],
  'date': ['اختر التاريخ', 'Select date'],
};

const leaseEnumArabic = <String, List<String>>{
  'status': [
    'مسودة',
    'بانتظار التوقيع',
    'نشط',
    'منتهي',
    'مجدّد',
    'تم إنهاؤه',
    'ملغى',
    'مستبدل',
  ],
  'frequency': ['شهري', 'ربع سنوي', 'نصف سنوي', 'سنوي'],
  'regime': ['قياسي', 'قانون الإيجار القديم'],
  'tenantType': ['فرد', 'شركة'],
  'termination': [
    'انتهاء طبيعي',
    'إنهاء مبكر',
    'اتفاق متبادل',
    'طلب المستأجر',
    'طلب المالك',
    'إخلاء قانوني',
  ],
  'document': ['عقد موقّع', 'نسخة الهوية', 'جواز سفر', 'إثبات دخل', 'أخرى'],
  'sync': [
    'لم تتم المزامنة',
    'جارٍ المزامنة',
    'تمت المزامنة',
    'خطأ المزود',
    'تجاوز حد الطلبات',
    'انتهت المهلة',
    'معلّق',
    'حساب غير صالح',
  ],
};
const leaseEnumEnglish = <String, List<String>>{
  'status': [
    'Draft',
    'Pending signature',
    'Active',
    'Expired',
    'Renewed',
    'Terminated',
    'Cancelled',
    'Superseded',
  ],
  'frequency': ['Monthly', 'Quarterly', 'Semiannual', 'Annual'],
  'regime': ['Standard', 'Old rent law'],
  'tenantType': ['Personal', 'Corporate'],
  'termination': [
    'Normal expiration',
    'Early termination',
    'Mutual agreement',
    'Tenant request',
    'Owner request',
    'Legal eviction',
  ],
  'document': [
    'Signed contract',
    'National ID copy',
    'Passport',
    'Income proof',
    'Other',
  ],
  'sync': [
    'Never synced',
    'Syncing',
    'Synced',
    'Provider error',
    'Rate limited',
    'Timeout',
    'Suspended',
    'Invalid account',
  ],
};
String le(BuildContext context, String group, int index) =>
    leaseEnumLabel(group, index, context.isArabic);
String leaseEnumLabel(String group, int index, bool arabic) {
  final items = (arabic ? leaseEnumArabic : leaseEnumEnglish)[group]!;
  return index >= 0 && index < items.length
      ? items[index]
      : leaseText('unknown', arabic);
}
