using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using PropertyOS.Domain.Companies;
using PropertyOS.Domain.Companies.Enums;

namespace PropertyOS.Infrastructure.Companies.Configurations;

/// <summary>
/// EF Core configuration for the <see cref="Company"/> entity.
/// Maps column-for-column and constraint-for-constraint to the approved
/// physical database design for the `companies` table (Module 1 §1.1).
///
/// Every mapping detail is explicit — EF Core conventions are not relied upon
/// where an approved physical definition already exists.
/// </summary>
internal sealed class CompanyConfiguration : IEntityTypeConfiguration<Company>
{
    public void Configure(EntityTypeBuilder<Company> builder)
    {
        // -----------------------------------------------------------------------
        // Table and schema
        // -----------------------------------------------------------------------
        builder.ToTable("companies", t =>
        {
            // chk_companies_primary_phone_format: +962 E.164 format validation
            // PostgreSQL regex: ^\+962[0-9]{8,9}$  (E.164 Jordanian format)
            t.HasCheckConstraint(
                "chk_companies_primary_phone_format",
                "primary_phone ~ '^\\+962[0-9]{8,9}$'");
        });

        // -----------------------------------------------------------------------
        // Primary key — UUID v7 generated by PostgreSQL DEFAULT uuid_generate_v7()
        // EF Core reads the generated value back via RETURNING on INSERT.
        // ValueGeneratedOnAdd tells EF Core to expect the database to supply
        // the value; HasDefaultValueSql provides the SQL expression for DDL.
        // -----------------------------------------------------------------------
        builder.HasKey(c => c.Id);

        builder.Property(c => c.Id)
            .HasColumnName("id")
            .HasColumnType("uuid")
            .HasDefaultValueSql("uuid_generate_v7()")
            .ValueGeneratedOnAdd();

        // -----------------------------------------------------------------------
        // Core identity columns
        // -----------------------------------------------------------------------

        builder.Property(c => c.LegalName)
            .HasColumnName("legal_name")
            .HasColumnType("character varying(255)")
            .HasMaxLength(255)
            .IsRequired();

        builder.Property(c => c.DisplayName)
            .HasColumnName("display_name")
            .HasColumnType("character varying(255)")
            .HasMaxLength(255)
            .IsRequired();

        builder.Property(c => c.CommercialRegistrationNo)
            .HasColumnName("commercial_registration_no")
            .HasColumnType("character varying(50)")
            .HasMaxLength(50)
            .IsRequired(false);

        builder.Property(c => c.TaxNumber)
            .HasColumnName("tax_number")
            .HasColumnType("character varying(50)")
            .HasMaxLength(50)
            .IsRequired(false);

        // PostgreSQL enum — mapped via Npgsql native enum support.
        // The C# enum CompanyType maps to PostgreSQL enum company_type_enum.
        // Npgsql's DefaultNameTranslator converts PascalCase → snake_case labels.
        builder.Property(c => c.CompanyType)
            .HasColumnName("company_type")
            .HasColumnType("company_type_enum")
            .HasDefaultValue(CompanyType.IndividualOwner)
            .IsRequired();

        builder.Property(c => c.PrimaryPhone)
            .HasColumnName("primary_phone")
            .HasColumnType("character varying(20)")
            .HasMaxLength(20)
            .IsRequired();

        builder.Property(c => c.PrimaryEmail)
            .HasColumnName("primary_email")
            .HasColumnType("character varying(255)")
            .HasMaxLength(255)
            .IsRequired(false);

        builder.Property(c => c.CountryCode)
            .HasColumnName("country_code")
            .HasColumnType("character(2)")
            .HasMaxLength(2)
            .HasDefaultValue("JO")
            .IsRequired();

        builder.Property(c => c.IsActive)
            .HasColumnName("is_active")
            .HasColumnType("boolean")
            .HasDefaultValue(true)
            .IsRequired();

        // -----------------------------------------------------------------------
        // Audit columns — TIMESTAMPTZ / UUID per Global Conventions
        // -----------------------------------------------------------------------

        builder.Property(c => c.CreatedAt)
            .HasColumnName("created_at")
            .HasColumnType("timestamp with time zone")
            .HasDefaultValueSql("now()")
            .IsRequired();

        builder.Property(c => c.UpdatedAt)
            .HasColumnName("updated_at")
            .HasColumnType("timestamp with time zone")
            .HasDefaultValueSql("now()")
            .IsRequired();

        // created_by / updated_by / deleted_by → users(id) nullable FKs.
        // These are deferred/nullable circular references (users.company_id exists,
        // but companies.created_by → users is the start of the onboarding bootstrap).
        // Configured as simple UUID columns here — the FK relationship to users
        // will be configured in Module 3 when the User entity is implemented.
        builder.Property(c => c.CreatedBy)
            .HasColumnName("created_by")
            .HasColumnType("uuid")
            .IsRequired(false);

        builder.Property(c => c.UpdatedBy)
            .HasColumnName("updated_by")
            .HasColumnType("uuid")
            .IsRequired(false);

        // -----------------------------------------------------------------------
        // Soft-delete columns
        // -----------------------------------------------------------------------

        builder.Property(c => c.DeletedAt)
            .HasColumnName("deleted_at")
            .HasColumnType("timestamp with time zone")
            .IsRequired(false);

        builder.Property(c => c.DeletedBy)
            .HasColumnName("deleted_by")
            .HasColumnType("uuid")
            .IsRequired(false);

        // -----------------------------------------------------------------------
        // Unique constraints
        // -----------------------------------------------------------------------

        // Partial unique: uq_companies_commercial_registration_no
        // WHERE commercial_registration_no IS NOT NULL
        // EF Core cannot express the WHERE clause via HasAlternateKey/HasIndex fluent API —
        // this index is hand-appended in the migration SQL.
        // The HasIndex call here establishes the index name for EF Core's metadata;
        // the actual WHERE clause is added in raw SQL in the migration.
        builder.HasIndex(c => c.CommercialRegistrationNo)
            .HasDatabaseName("uq_companies_commercial_registration_no")
            .IsUnique();
        // NOTE: The partial WHERE clause is added via raw SQL in the migration.
        // The index as generated by EF Core will be a full unique index; the migration
        // then drops it and recreates it as a partial index. See migration comments.

        // -----------------------------------------------------------------------
        // Indexes
        // -----------------------------------------------------------------------

        // idx_companies_deleted_at (partial) — WHERE deleted_at IS NULL
        // Listed here for metadata; the WHERE clause is in migration raw SQL.
        builder.HasIndex(c => c.DeletedAt)
            .HasDatabaseName("idx_companies_deleted_at");

        // idx_companies_commercial_registration_no — supports admin lookup.
        // Distinct from the unique constraint index; the unique index already
        // provides the B-tree access path. The unique constraint IS the lookup
        // index — no separate plain index needed. This follows the approved
        // Physical Design §1.1: the unique constraint's implicit B-tree serves
        // both uniqueness enforcement and the lookup requirement simultaneously.
        // (No additional idx_companies_commercial_registration_no is created —
        // the partial unique index covers this need, per the approved design.)

        // -----------------------------------------------------------------------
        // One-to-one relationship to CompanySettings
        // -----------------------------------------------------------------------

        builder.HasOne(c => c.Settings)
            .WithOne(s => s.Company)
            .HasForeignKey<CompanySettings>(s => s.CompanyId)
            .OnDelete(DeleteBehavior.Cascade);

        // -----------------------------------------------------------------------
        // Global query filter: soft-delete + tenant isolation
        //
        // companies is the tenant ROOT — it is NOT scoped by company_id itself.
        // The only global query filter applied here is the soft-delete filter.
        // Tenant-scoped child tables will have a CompanyId filter in their own
        // configurations.
        //
        // Platform-admin bypass of the soft-delete filter is supported via
        // EF Core 9's selective IgnoreQueryFilters per-filter (not implemented
        // here — the filter itself is registered; selective ignore is at call site).
        // -----------------------------------------------------------------------
        builder.HasQueryFilter(c => c.DeletedAt == null);

        // -----------------------------------------------------------------------
        // Concurrency token — PostgreSQL xmin system column
        // Provides optimistic concurrency on every entity for free without
        // adding a row_version column the approved schema doesn't define.
        // (Architecture §6: ".IsRowVersion() via .HasColumnName("xmin")")
        // -----------------------------------------------------------------------
        builder.Property<uint>("xmin")
            .HasColumnName("xmin")
            .HasColumnType("xid")
            .IsRowVersion();
    }
}
