using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using PropertyOS.Domain.Companies;
using PropertyOS.Domain.Companies.Enums;

namespace PropertyOS.Infrastructure.Companies.Configurations;

/// <summary>
/// EF Core configuration for the <see cref="CompanySettings"/> entity.
/// Maps column-for-column and constraint-for-constraint to the approved
/// physical database design for the `company_settings` table (Module 1 §1.2).
///
/// CRITICAL lifecycle invariants enforced here:
///   • No soft-delete — no DeletedAt / DeletedBy columns.
///   • No created_by / updated_by audit FKs — only created_at / updated_at.
///   • FK to companies ON DELETE CASCADE (no independent lifecycle).
///   • Unique constraint on company_id enforces strict 1:1 cardinality.
/// </summary>
internal sealed class CompanySettingsConfiguration : IEntityTypeConfiguration<CompanySettings>
{
    public void Configure(EntityTypeBuilder<CompanySettings> builder)
    {
        // -----------------------------------------------------------------------
        // Table and schema
        // -----------------------------------------------------------------------
        builder.ToTable("company_settings", t =>
        {
            // chk_company_settings_fiscal_month: fiscal_year_start_month BETWEEN 1 AND 12
            t.HasCheckConstraint(
                "chk_company_settings_fiscal_month",
                "fiscal_year_start_month BETWEEN 1 AND 12");

            // chk_company_settings_late_fee_value:
            //   (late_fee_type = 'none' → late_fee_value IS NULL)
            //   (late_fee_type != 'none' → late_fee_value IS NOT NULL)
            t.HasCheckConstraint(
                "chk_company_settings_late_fee_value",
                "(late_fee_type = 'none' AND late_fee_value IS NULL) OR " +
                "(late_fee_type != 'none' AND late_fee_value IS NOT NULL)");
        });

        // -----------------------------------------------------------------------
        // Primary key — UUID v7 generated by PostgreSQL DEFAULT uuid_generate_v7()
        // -----------------------------------------------------------------------
        builder.HasKey(s => s.Id);

        builder.Property(s => s.Id)
            .HasColumnName("id")
            .HasColumnType("uuid")
            .HasDefaultValueSql("uuid_generate_v7()")
            .ValueGeneratedOnAdd();

        // -----------------------------------------------------------------------
        // Foreign key column — company_id (the 1:1 ownership link)
        // -----------------------------------------------------------------------
        builder.Property(s => s.CompanyId)
            .HasColumnName("company_id")
            .HasColumnType("uuid")
            .IsRequired();

        // -----------------------------------------------------------------------
        // Configuration columns
        // -----------------------------------------------------------------------

        builder.Property(s => s.DefaultCurrency)
            .HasColumnName("default_currency")
            .HasColumnType("character(3)")
            .HasMaxLength(3)
            .HasDefaultValue("JOD")
            .IsRequired();

        builder.Property(s => s.RentGracePeriodDays)
            .HasColumnName("rent_grace_period_days")
            .HasColumnType("smallint")
            .HasDefaultValue((short)5)
            .IsRequired();

        // PostgreSQL enum — late_fee_type_enum
        // Npgsql's DefaultNameTranslator maps: None→none, Fixed→fixed, Percentage→percentage
        builder.Property(s => s.LateFeeType)
            .HasColumnName("late_fee_type")
            .HasColumnType("late_fee_type_enum")
            .HasDefaultValue(LateFeeType.None)
            .IsRequired();

        // NUMERIC(12,3) — approved money type per Global Conventions
        // NULL is valid when late_fee_type = 'none'
        builder.Property(s => s.LateFeeValue)
            .HasColumnName("late_fee_value")
            .HasColumnType("numeric(12,3)")
            .IsRequired(false);

        builder.Property(s => s.FiscalYearStartMonth)
            .HasColumnName("fiscal_year_start_month")
            .HasColumnType("smallint")
            .HasDefaultValue((short)1)
            .IsRequired();

        builder.Property(s => s.DefaultLanguage)
            .HasColumnName("default_language")
            .HasColumnType("character(2)")
            .HasMaxLength(2)
            .HasDefaultValue("ar")
            .IsRequired();

        builder.Property(s => s.Timezone)
            .HasColumnName("timezone")
            .HasColumnType("character varying(50)")
            .HasMaxLength(50)
            .HasDefaultValue("Asia/Amman")
            .IsRequired();

        // -----------------------------------------------------------------------
        // Audit columns — ONLY created_at / updated_at per approved Physical Design §1.2
        // No created_by / updated_by here (differs from Global Convention —
        // explicitly noted in Physical Design: company_settings omits those FKs).
        // -----------------------------------------------------------------------

        builder.Property(s => s.CreatedAt)
            .HasColumnName("created_at")
            .HasColumnType("timestamp with time zone")
            .HasDefaultValueSql("now()")
            .IsRequired();

        builder.Property(s => s.UpdatedAt)
            .HasColumnName("updated_at")
            .HasColumnType("timestamp with time zone")
            .HasDefaultValueSql("now()")
            .IsRequired();

        // -----------------------------------------------------------------------
        // Unique constraint — enforces 1:1 cardinality at the database level
        // uq_company_settings_company_id on (company_id)
        // -----------------------------------------------------------------------
        builder.HasIndex(s => s.CompanyId)
            .HasDatabaseName("uq_company_settings_company_id")
            .IsUnique();


        // -----------------------------------------------------------------------
        // Relationship — configured on both sides; FK ON DELETE CASCADE from Company
        // The HasOne/WithOne is declared here on the dependent (CompanySettings);
        // CompanyConfiguration also declares it from the principal side.
        // EF Core resolves both declarations to one consistent FK configuration.
        // -----------------------------------------------------------------------
        builder.HasOne(s => s.Company)
            .WithOne(c => c.Settings)
            .HasForeignKey<CompanySettings>(s => s.CompanyId)
            .OnDelete(DeleteBehavior.Cascade);

        // -----------------------------------------------------------------------
        // NO global query filter for company_settings:
        //   • No soft-delete filter (no deleted_at column).
        //   • No standalone tenant filter — this table is always accessed through
        //     its parent Company, whose own query filter already scopes results.
        //     The unique constraint on company_id guarantees one row per company;
        //     the database-level ON DELETE CASCADE is the authoritative lifecycle gate.
        // -----------------------------------------------------------------------

        // -----------------------------------------------------------------------
        // Concurrency token — PostgreSQL xmin system column
        // -----------------------------------------------------------------------
        builder.Property<uint>("xmin")
            .HasColumnName("xmin")
            .HasColumnType("xid")
            .IsRowVersion();
    }
}
