using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using PropertyOS.Domain.Properties;
using PropertyOS.Domain.Properties.Enums;

namespace PropertyOS.Infrastructure.Properties.Configurations;

/// <summary>
/// EF Core configuration for the <see cref="Building"/> entity.
/// Maps column-for-column and constraint-for-constraint to the approved
/// physical database design for the <c>buildings</c> table (Module 4 §4.1).
///
/// REDUNDANT INDEX REPORT:
///   EF Core will NOT automatically create an index on company_id alone from
///   the HasForeignKey relationship, because this is not the leading column of
///   the composite candidate key uq_buildings_company_id. The partial indexes
///   idx_buildings_company_id and idx_buildings_company_active are created
///   entirely in raw SQL in the migration — no EF index metadata creates a
///   duplicate. The candidate key UNIQUE(company_id, id) produces an EF-managed
///   index named uq_buildings_company_id; no duplicate of this is added.
/// </summary>
internal sealed class BuildingConfiguration : IEntityTypeConfiguration<Building>
{
    public void Configure(EntityTypeBuilder<Building> builder)
    {
        // -----------------------------------------------------------------------
        // Table
        // -----------------------------------------------------------------------
        builder.ToTable("buildings", t =>
        {
            t.HasCheckConstraint(
                "chk_buildings_total_floors_positive",
                "total_floors > 0");

            t.HasCheckConstraint(
                "chk_buildings_construction_year_range",
                "construction_year IS NULL OR (construction_year BETWEEN 1900 AND EXTRACT(YEAR FROM CURRENT_DATE)::SMALLINT + 5)");

            t.HasCheckConstraint(
                "chk_buildings_gps_pair",
                "(gps_latitude IS NULL) = (gps_longitude IS NULL)");
        });

        // -----------------------------------------------------------------------
        // Primary Key — UUID v7 generated by PostgreSQL DEFAULT uuid_generate_v7()
        // -----------------------------------------------------------------------
        builder.HasKey(b => b.Id);

        builder.Property(b => b.Id)
            .HasColumnName("id")
            .HasColumnType("uuid")
            .HasDefaultValueSql("uuid_generate_v7()")
            .ValueGeneratedOnAdd();

        // -----------------------------------------------------------------------
        // Tenant key
        // -----------------------------------------------------------------------

        builder.Property(b => b.CompanyId)
            .HasColumnName("company_id")
            .HasColumnType("uuid")
            .IsRequired();

        // -----------------------------------------------------------------------
        // Core columns
        // -----------------------------------------------------------------------

        builder.Property(b => b.Name)
            .HasColumnName("name")
            .HasColumnType("character varying(255)")
            .HasMaxLength(255)
            .IsRequired();

        builder.Property(b => b.InternalCode)
            .HasColumnName("internal_code")
            .HasColumnType("character varying(50)")
            .HasMaxLength(50)
            .IsRequired(false);

        builder.Property(b => b.BuildingType)
            .HasColumnName("building_type")
            .HasColumnType("building_type_enum")
            .HasDefaultValueSql("'residential'")
            .IsRequired();

        builder.Property(b => b.TotalFloors)
            .HasColumnName("total_floors")
            .HasColumnType("smallint")
            .IsRequired();

        builder.Property(b => b.ConstructionYear)
            .HasColumnName("construction_year")
            .HasColumnType("smallint")
            .IsRequired(false);

        builder.Property(b => b.GpsLatitude)
            .HasColumnName("gps_latitude")
            .HasColumnType("numeric(10,7)")
            .IsRequired(false);

        builder.Property(b => b.GpsLongitude)
            .HasColumnName("gps_longitude")
            .HasColumnType("numeric(10,7)")
            .IsRequired(false);

        builder.Property(b => b.TotalApartmentsCount)
            .HasColumnName("total_apartments_count")
            .HasColumnType("integer")
            .HasDefaultValue(0)
            .IsRequired();

        builder.Property(b => b.IsActive)
            .HasColumnName("is_active")
            .HasColumnType("boolean")
            .HasDefaultValue(true)
            .IsRequired();

        // -----------------------------------------------------------------------
        // Audit columns
        // -----------------------------------------------------------------------

        builder.Property(b => b.CreatedAt)
            .HasColumnName("created_at")
            .HasColumnType("timestamp with time zone")
            .HasDefaultValueSql("now()")
            .IsRequired();

        builder.Property(b => b.UpdatedAt)
            .HasColumnName("updated_at")
            .HasColumnType("timestamp with time zone")
            .HasDefaultValueSql("now()")
            .IsRequired();

        builder.Property(b => b.CreatedBy)
            .HasColumnName("created_by")
            .HasColumnType("uuid")
            .IsRequired(false);

        builder.Property(b => b.UpdatedBy)
            .HasColumnName("updated_by")
            .HasColumnType("uuid")
            .IsRequired(false);

        // -----------------------------------------------------------------------
        // Soft-delete columns
        // -----------------------------------------------------------------------

        builder.Property(b => b.DeletedAt)
            .HasColumnName("deleted_at")
            .HasColumnType("timestamp with time zone")
            .IsRequired(false);

        builder.Property(b => b.DeletedBy)
            .HasColumnName("deleted_by")
            .HasColumnType("uuid")
            .IsRequired(false);

        // -----------------------------------------------------------------------
        // FK: company_id → companies(id) ON DELETE RESTRICT
        // -----------------------------------------------------------------------
        builder.HasOne<PropertyOS.Domain.Companies.Company>()
            .WithMany()
            .HasForeignKey(b => b.CompanyId)
            .HasConstraintName("FK_buildings_companies_company_id")
            .OnDelete(DeleteBehavior.Restrict);

        // -----------------------------------------------------------------------
        // FK: created_by / updated_by / deleted_by → users(id) ON DELETE SET NULL
        // -----------------------------------------------------------------------
        builder.HasOne<PropertyOS.Domain.Identity.Entities.User>()
            .WithMany()
            .HasForeignKey(b => b.CreatedBy)
            .HasConstraintName("FK_buildings_users_created_by")
            .OnDelete(DeleteBehavior.SetNull);

        builder.HasOne<PropertyOS.Domain.Identity.Entities.User>()
            .WithMany()
            .HasForeignKey(b => b.UpdatedBy)
            .HasConstraintName("FK_buildings_users_updated_by")
            .OnDelete(DeleteBehavior.SetNull);

        builder.HasOne<PropertyOS.Domain.Identity.Entities.User>()
            .WithMany()
            .HasForeignKey(b => b.DeletedBy)
            .HasConstraintName("FK_buildings_users_deleted_by")
            .OnDelete(DeleteBehavior.SetNull);

        // -----------------------------------------------------------------------
        // Candidate key: UNIQUE(company_id, id)
        // Required by the composite FK from floors and building_addresses:
        //   floors(company_id, building_id) → buildings(company_id, id)
        //   building_addresses(company_id, building_id) → buildings(company_id, id)
        //
        // NOTE: EF Core will generate an index for this candidate key named
        // "uq_buildings_company_id" automatically. No additional partial index
        // for (company_id) alone is registered here — that partial index is
        // created in raw SQL in the migration.
        // -----------------------------------------------------------------------
        builder.HasAlternateKey(b => new { b.CompanyId, b.Id })
            .HasName("uq_buildings_company_id");

        // -----------------------------------------------------------------------
        // Partial unique index on internal_code (per-company, excludes NULLs and
        // soft-deleted rows). WHERE clause applied in migration raw SQL.
        // EF metadata registration only — the actual partial index is hand-crafted
        // in the migration.
        // -----------------------------------------------------------------------
        builder.HasIndex(b => new { b.CompanyId, b.InternalCode })
            .HasDatabaseName("uq_buildings_company_internal_code")
            .IsUnique();
        // NOTE: migration drops this EF-generated full unique index and recreates
        // it as:
        //   CREATE UNIQUE INDEX uq_buildings_company_internal_code
        //     ON buildings(company_id, internal_code)
        //     WHERE internal_code IS NOT NULL AND deleted_at IS NULL;

        // -----------------------------------------------------------------------
        // 1:1 relationship to BuildingAddress
        // -----------------------------------------------------------------------
        builder.HasOne(b => b.Address)
            .WithOne(a => a.Building)
            .HasPrincipalKey<Building>(b => new { b.CompanyId, b.Id })
            .HasForeignKey<BuildingAddress>(a => new { a.CompanyId, a.BuildingId })
            .HasConstraintName("fk_building_addresses_buildings_company_building")
            .OnDelete(DeleteBehavior.Cascade);

        // -----------------------------------------------------------------------
        // 1:N relationship to Floors
        // -----------------------------------------------------------------------
        builder.HasMany(b => b.Floors)
            .WithOne()
            .HasPrincipalKey(b => new { b.CompanyId, b.Id })
            .HasForeignKey(f => new { f.CompanyId, f.BuildingId })
            .HasConstraintName("fk_floors_buildings_company_building")
            .OnDelete(DeleteBehavior.Restrict);

        // -----------------------------------------------------------------------
        // Global query filter: soft-delete only (company_id scope via RLS)
        // -----------------------------------------------------------------------
        builder.HasQueryFilter(b => b.DeletedAt == null);

        // -----------------------------------------------------------------------
        // Concurrency token — PostgreSQL xmin system column
        // -----------------------------------------------------------------------
        builder.Property<uint>("xmin")
            .HasColumnName("xmin")
            .HasColumnType("xid")
            .IsRowVersion();
    }
}
