export const mvpEn = {
  addDocument: "Add document",
  editDocument: "Edit metadata",
  replaceFile: "Replace file",
  deleteDocument: "Delete document",
  deleteDocumentNote:
    "This document will no longer appear among active building documents.",
  noBuildings: "No buildings available.",
  noDocuments: "No documents for this building.",
  noMatchingDocuments: "No matching documents.",
  file: "File",
  chooseCategory: "Select a category",
  noCategories:
    "No categories available. Create a category in Document categories, or ask an administrator.",
  requestUpload: "Preparing upload…",
  uploading: "Uploading file…",
  confirmingUpload: "Confirming upload…",
  savingDocument: "Saving document…",
  uploadFailure:
    "File upload failed. Check the file and connection, then try again.",
  fileRequired: "Select a non-empty file.",
  chooseFile: "Choose a file",
  chooseFileHint: "Click to select from your device",
  changeFile: "Change file",
  removeFile: "Remove selected file",
  supportedDocumentFiles:
    "PDF, Word (DOCX), Excel (XLSX), or image (PNG, JPG, WEBP)",
  documentValidation:
    "Enter a document name (up to 255 characters), description (up to 2,000), and valid dates. Expiry must be after issue date; issue date cannot be in the future.",
  openFile: "Open file",
  openFileNote:
    "If the file did not open automatically, use this link. If it expires, request Download again.",
  replaceNote:
    "Upload a new file. The existing category and metadata are preserved.",
  individualOwner: "Individual owner",
  managementCompany: "Property management company",
  investmentCompany: "Investment company",
  parking: "Parking & Garages",
  spots: "Building parking spots",
  building: "Building",
  chooseBuilding: "Select a building",
  code: "Spot code",
  type: "Parking type",
  location: "Location description",
  apartment: "Default apartment",
  none: "None",
  standard: "Standard",
  covered: "Covered",
  visitor: "Visitor",
  accessible: "Accessible",
  active: "Active",
  inactive: "Inactive",
  create: "Create",
  edit: "Edit",
  archive: "Archive",
  delete: "Delete",
  save: "Save",
  cancel: "Cancel",
  close: "Close",
  confirm: "Confirm",
  archiveConfirm: "Archive this parking spot?",
  deleteConfirm: "Delete this category?",
  archiveNote:
    "This archives the record. Existing dependencies may prevent this action.",
  deleteNote: "Categories in use cannot be deleted.",
  refresh: "Refresh",
  loading: "Loading…",
  empty: "No records found.",
  error: "Unable to complete the request.",
  denied: "You do not have access to this resource.",
  required: "Check the required fields and allowed values.",
  saved: "Changes saved.",
  previous: "Previous",
  next: "Next",
  page: "Page",
  documents: "Documents",
  categories: "Document categories",
  name: "Name",
  description: "Description",
  search: "Document name",
  apply: "Search",
  all: "All categories",
  documentsNote: "Select a building to view and manage its documents.",
  detail: "Details",
  issueDate: "Issue date",
  expiryDate: "Expiry date",
  createdAt: "Created",
  confidential: "Confidential",
  ordinary: "Ordinary",
  filename: "Original filename",
  mime: "File type",
  size: "Size (bytes)",
  uploadedBy: "Uploaded by",
  download: "Download",
  categoryInUse:
    "This category is referenced by building documents and cannot be deleted.",
  notifications: "Notifications",
  markRead: "Mark read",
  markAll: "Mark all read",
  marked: "Notifications marked as read: {{count}}",
  unread: "Unread: {{count}}",
  pending: "Pending",
  sent: "Sent",
  failed: "Failed",
  cancelled: "Cancelled",
  read: "Read",
  settings: "Settings",
  companyProfile: "Company profile",
  operations: "Operational settings",
  legalName: "Legal name",
  displayName: "Display name",
  phone: "Phone",
  email: "Email",
  registration: "Commercial registration",
  tax: "Tax number",
  country: "Country",
  companyType: "Company type",
  grace: "Rent grace period (days)",
  feeType: "Late fee type",
  feeValue: "Late fee value",
  fixed: "Fixed",
  percentage: "Percentage",
  fiscal: "Fiscal year start month",
  currency: "Default currency",
  language: "Language",
  timezone: "Timezone",
  appearance: "Appearance",
  light: "Light",
  dark: "Dark",
  system: "System",
  profile: "Your profile",
  logout: "Sign out",
  logoutAll: "Sign out on all devices",
  logoutAllNote: "Revoke your refresh sessions on all devices?",
  recovery: "Password recovery",
  subscription: "Subscription",
  newLease: "New lease",
  leaseExpiration: "Lease expiration",
  rentDue: "Rent due",
  rentPaid: "Rent paid",
  latePayment: "Late payment",
  maintenanceCreated: "Maintenance request",
  maintenanceUpdated: "Maintenance update",
  marketplace: "Viewing request",
  documentExpiring: "Document expiring",
  general: "General notification",
  electricity: "Electricity bill",
  water: "Water bill",
};
export const mvpAr: Record<keyof typeof mvpEn, string> = {
  addDocument: "إضافة مستند",
  editDocument: "تعديل البيانات",
  replaceFile: "استبدال الملف",
  deleteDocument: "حذف المستند",
  deleteDocumentNote:
    "هل أنت متأكد من حذف هذا المستند؟ لن يظهر ضمن المستندات النشطة بعد الحذف.",
  noBuildings: "لا توجد مبانٍ متاحة.",
  noDocuments: "لا توجد مستندات لهذا المبنى.",
  noMatchingDocuments: "لا توجد مستندات مطابقة.",
  file: "الملف",
  chooseCategory: "اختر تصنيفاً",
  noCategories:
    "لا توجد تصنيفات متاحة. أضف تصنيفاً من تصنيفات المستندات أو تواصل مع المسؤول.",
  requestUpload: "جارٍ تجهيز الرفع…",
  uploading: "جارٍ رفع الملف…",
  confirmingUpload: "جارٍ تأكيد الرفع…",
  savingDocument: "جارٍ حفظ المستند…",
  uploadFailure: "تعذر رفع الملف. تحقق من الملف والاتصال ثم أعد المحاولة.",
  fileRequired: "اختر ملفاً غير فارغ.",
  chooseFile: "اختر ملفًا",
  chooseFileHint: "اضغط لاختيار ملف من جهازك",
  changeFile: "تغيير الملف",
  removeFile: "إزالة الملف المحدد",
  supportedDocumentFiles:
    "PDF أو Word (DOCX) أو Excel (XLSX) أو صورة (PNG، JPG، WEBP)",
  documentValidation:
    "أدخل اسم المستند (حتى ٢٥٥ حرفاً) والوصف (حتى ٢٠٠٠ حرف) وتواريخ صحيحة. يجب أن يلي الانتهاء تاريخ الإصدار وألا يكون الإصدار في المستقبل.",
  openFile: "فتح الملف",
  openFileNote:
    "إذا لم يفتح الملف تلقائياً، استخدم هذا الرابط. إذا انتهت صلاحيته، اطلب التنزيل مجدداً.",
  replaceNote: "ارفع ملفاً جديداً. سيبقى التصنيف والبيانات الحالية كما هي.",
  individualOwner: "مالك فردي",
  managementCompany: "شركة إدارة عقارات",
  investmentCompany: "شركة استثمار",
  parking: "المواقف والكراجات",
  spots: "مواقف السيارات في المبنى",
  building: "المبنى",
  chooseBuilding: "اختر مبنى",
  code: "رمز الموقف",
  type: "نوع الموقف",
  location: "وصف الموقع",
  apartment: "الوحدة الافتراضية",
  none: "بدون",
  standard: "عادي",
  covered: "مغطى",
  visitor: "زوار",
  accessible: "ذوو الإعاقة",
  active: "نشط",
  inactive: "غير نشط",
  create: "إنشاء",
  edit: "تعديل",
  archive: "أرشفة",
  delete: "حذف",
  save: "حفظ",
  cancel: "إلغاء",
  close: "إغلاق",
  confirm: "تأكيد",
  archiveConfirm: "أرشفة هذا الموقف؟",
  deleteConfirm: "حذف هذا التصنيف؟",
  archiveNote: "ستتم أرشفة السجل. قد تمنع الارتباطات الحالية هذا الإجراء.",
  deleteNote: "لا يمكن حذف التصنيفات المستخدمة.",
  refresh: "تحديث",
  loading: "جارٍ التحميل…",
  empty: "لا توجد سجلات.",
  error: "تعذر إكمال الطلب.",
  denied: "ليس لديك صلاحية للوصول إلى هذا السجل.",
  required: "تحقق من الحقول المطلوبة والقيم المسموحة.",
  saved: "تم حفظ التغييرات.",
  previous: "السابق",
  next: "التالي",
  page: "الصفحة",
  documents: "المستندات",
  categories: "تصنيفات المستندات",
  name: "الاسم",
  description: "الوصف",
  search: "اسم المستند",
  apply: "بحث",
  all: "جميع التصنيفات",
  documentsNote: "اختر مبنى لعرض مستنداته وإدارتها.",
  detail: "التفاصيل",
  issueDate: "تاريخ الإصدار",
  expiryDate: "تاريخ الانتهاء",
  createdAt: "تاريخ الإنشاء",
  confidential: "سري",
  ordinary: "عادي",
  filename: "اسم الملف الأصلي",
  mime: "نوع الملف",
  size: "الحجم (بايت)",
  uploadedBy: "رُفع بواسطة",
  download: "تنزيل",
  categoryInUse: "هذا التصنيف مرتبط بمستندات مبانٍ ولا يمكن حذفه.",
  notifications: "الإشعارات",
  markRead: "تحديد كمقروء",
  markAll: "تحديد الكل كمقروء",
  marked: "عدد الإشعارات المحددة كمقروءة: {{count}}",
  unread: "غير المقروء: {{count}}",
  pending: "قيد الانتظار",
  sent: "مرسل",
  failed: "فشل الإرسال",
  cancelled: "ملغى",
  read: "مقروء",
  settings: "الإعدادات",
  companyProfile: "بيانات الشركة",
  operations: "الإعدادات التشغيلية",
  legalName: "الاسم القانوني",
  displayName: "اسم العرض",
  phone: "الهاتف",
  email: "البريد الإلكتروني",
  registration: "السجل التجاري",
  tax: "الرقم الضريبي",
  country: "الدولة",
  companyType: "نوع الشركة",
  grace: "فترة السماح للإيجار (أيام)",
  feeType: "نوع غرامة التأخير",
  feeValue: "قيمة غرامة التأخير",
  fixed: "مبلغ ثابت",
  percentage: "نسبة مئوية",
  fiscal: "شهر بدء السنة المالية",
  currency: "العملة الافتراضية",
  language: "اللغة",
  timezone: "المنطقة الزمنية",
  appearance: "المظهر",
  light: "فاتح",
  dark: "داكن",
  system: "النظام",
  profile: "ملفك الشخصي",
  logout: "تسجيل الخروج",
  logoutAll: "الخروج من جميع الأجهزة",
  logoutAllNote: "إلغاء جلسات التجديد على جميع أجهزتك؟",
  recovery: "استعادة كلمة المرور",
  subscription: "الاشتراك",
  newLease: "عقد جديد",
  leaseExpiration: "انتهاء عقد",
  rentDue: "إيجار مستحق",
  rentPaid: "إيجار مدفوع",
  latePayment: "دفعة متأخرة",
  maintenanceCreated: "طلب صيانة",
  maintenanceUpdated: "تحديث صيانة",
  marketplace: "طلب معاينة",
  documentExpiring: "مستند ينتهي قريباً",
  general: "إشعار عام",
  electricity: "فاتورة كهرباء",
  water: "فاتورة مياه",
};
