using PropertyOS.Domain.Companies.Enums;

namespace PropertyOS.Domain.Companies;

/// <summary>
/// One-to-one configuration extension of Company.
/// Maps to the PostgreSQL table: company_settings (Module 1 — Core).
///
/// Approved columns (Physical Design §1.2):
///   id, company_id, default_currency, rent_grace_period_days, late_fee_type,
///   late_fee_value, fiscal_year_start_month, default_language, timezone,
///   created_at, updated_at.
///
/// IMPORTANT lifecycle semantics (must be honored exactly):
///   • NO soft-delete — this table has no independent lifecycle.
///   • Lifecycle is CASCADE-only from the parent Company (FK ON DELETE CASCADE).
///   • No deleted_at / deleted_by columns exist on this table.
///   • No created_by / updated_by audit columns (table has only created_at / updated_at).
///
/// RLS: looked up exclusively via company_id; covered by the unique constraint index.
/// </summary>
public class CompanySettings
{
    // ---------------------------------------------------------------------------
    // Primary Key — UUID v7 generated by PostgreSQL DEFAULT uuid_generate_v7()
    // ---------------------------------------------------------------------------
    public Guid Id { get; private set; }

    // ---------------------------------------------------------------------------
    // Foreign key — mandatory 1:1 link to owning Company
    // ---------------------------------------------------------------------------

    /// <summary>UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE.</summary>
    public Guid CompanyId { get; private set; }

    // ---------------------------------------------------------------------------
    // Configuration columns
    // ---------------------------------------------------------------------------

    /// <summary>ISO 4217 currency code. CHAR(3) NOT NULL DEFAULT 'JOD'.</summary>
    public string DefaultCurrency { get; private set; } = "JOD";

    /// <summary>
    /// Days after due date before a payment is flagged late.
    /// SMALLINT NOT NULL DEFAULT 5.
    /// </summary>
    public short RentGracePeriodDays { get; private set; } = 5;

    /// <summary>
    /// Late fee calculation mode. late_fee_type_enum NOT NULL DEFAULT 'none'.
    /// Approved values: None, Fixed, Percentage.
    /// </summary>
    public LateFeeType LateFeeType { get; private set; } = LateFeeType.None;

    /// <summary>
    /// Amount (Fixed) or percentage (Percentage) depending on LateFeeType.
    /// NUMERIC(12,3) NULL. NULL when LateFeeType = None.
    /// DB CHECK: late_fee_value IS NOT NULL WHEN late_fee_type != 'none'.
    /// </summary>
    public decimal? LateFeeValue { get; private set; }

    /// <summary>
    /// 1–12, representing the month the fiscal year starts.
    /// SMALLINT NOT NULL DEFAULT 1.
    /// DB CHECK: fiscal_year_start_month BETWEEN 1 AND 12.
    /// </summary>
    public short FiscalYearStartMonth { get; private set; } = 1;

    /// <summary>Display language. CHAR(2) NOT NULL DEFAULT 'ar'. Values: 'ar' | 'en'.</summary>
    public string DefaultLanguage { get; private set; } = "ar";

    /// <summary>IANA timezone identifier. VARCHAR(50) NOT NULL DEFAULT 'Asia/Amman'.</summary>
    public string Timezone { get; private set; } = "Asia/Amman";

    // ---------------------------------------------------------------------------
    // Audit columns — only created_at / updated_at (no created_by / updated_by
    // and no soft-delete columns, per Physical Design §1.2)
    // ---------------------------------------------------------------------------

    public DateTimeOffset CreatedAt { get; private set; }
    public DateTimeOffset UpdatedAt { get; private set; }

    // ---------------------------------------------------------------------------
    // Navigation — back reference to owning Company (optional navigation)
    // ---------------------------------------------------------------------------
    public Company? Company { get; private set; }

    // ---------------------------------------------------------------------------
    // EF Core requires a parameterless constructor (private to prevent misuse).
    // ---------------------------------------------------------------------------
    private CompanySettings() { }

    // ---------------------------------------------------------------------------
    // Factory — creates with approved Jordan-market defaults.
    // Called in the same application transaction that creates the Company row.
    // ---------------------------------------------------------------------------

    /// <summary>
    /// Creates a new CompanySettings with the approved default values for the
    /// Jordanian market. The <paramref name="companyId"/> must be the owning
    /// Company's confirmed ID (populated after the Company INSERT RETURNING).
    /// </summary>
    public static CompanySettings CreateWithDefaults(Guid companyId, DateTimeOffset createdAt)
    {
        if (companyId == Guid.Empty)
            throw new ArgumentException("CompanyId must be a valid (non-empty) Guid.", nameof(companyId));

        return new CompanySettings
        {
            // Id left as Guid.Empty; filled by PostgreSQL DEFAULT uuid_generate_v7().
            Id = Guid.Empty,
            CompanyId = companyId,
            DefaultCurrency = "JOD",
            RentGracePeriodDays = 5,
            LateFeeType = LateFeeType.None,
            LateFeeValue = null,
            FiscalYearStartMonth = 1,
            DefaultLanguage = "ar",
            Timezone = "Asia/Amman",
            CreatedAt = createdAt,
            UpdatedAt = createdAt
        };
    }

    // ---------------------------------------------------------------------------
    // Mutation — update individual settings fields
    // ---------------------------------------------------------------------------

    /// <summary>
    /// Updates the late fee policy. Enforces the application-level mirror of the
    /// DB CHECK: late_fee_value must be provided when late_fee_type != 'none'.
    /// The database constraint remains authoritative.
    /// </summary>
    public void UpdateLateFeePolicy(LateFeeType type, decimal? value, DateTimeOffset updatedAt)
    {
        if (type != LateFeeType.None && value is null)
            throw new ArgumentException(
                "A late fee value is required when late_fee_type is not 'none'.",
                nameof(value));

        if (type == LateFeeType.None && value.HasValue)
            throw new ArgumentException(
                "A late fee value must be null when late_fee_type is 'none'.",
                nameof(value));

        if (value.HasValue && value.Value <= 0)
            throw new ArgumentException("Late fee value must be positive.", nameof(value));

        LateFeeType = type;
        LateFeeValue = type == LateFeeType.None ? null : value;
        UpdatedAt = updatedAt;
    }

    /// <summary>
    /// Updates the fiscal year start month. The DB CHECK (1–12) is authoritative;
    /// this guard provides an earlier failure point.
    /// </summary>
    public void UpdateFiscalYearStartMonth(short month, DateTimeOffset updatedAt)
    {
        if (month is < 1 or > 12)
            throw new ArgumentOutOfRangeException(nameof(month), "Fiscal year start month must be between 1 and 12.");

        FiscalYearStartMonth = month;
        UpdatedAt = updatedAt;
    }

    /// <summary>Updates the grace period days (positive integer enforced).</summary>
    public void UpdateRentGracePeriodDays(short days, DateTimeOffset updatedAt)
    {
        if (days < 0)
            throw new ArgumentOutOfRangeException(nameof(days), "Grace period days cannot be negative.");

        RentGracePeriodDays = days;
        UpdatedAt = updatedAt;
    }

    /// <summary>Marks the row as updated (used by infrastructure layer).</summary>
    internal void Touch(DateTimeOffset updatedAt)
    {
        UpdatedAt = updatedAt;
    }
}
