using PropertyOS.Domain.Common;
using PropertyOS.Domain.Companies.Enums;

namespace PropertyOS.Domain.Companies;

/// <summary>
/// Represents the tenant root entity — a paying customer using PropertyOS.
/// Maps to the PostgreSQL table: companies (Module 1 — Core).
///
/// Approved columns (Physical Design §1.1):
///   id, legal_name, display_name, commercial_registration_no, tax_number,
///   company_type, primary_phone, primary_email, country_code, is_active,
///   created_at, updated_at, created_by, updated_by, deleted_at, deleted_by.
///
/// Soft-delete: YES (standard deleted_at / deleted_by).
/// RLS: companies is the tenant root; special RLS handling applies (see migration).
/// </summary>
public class Company : ISoftDeletable
{
    // ---------------------------------------------------------------------------
    // Primary Key — UUID v7 generated by PostgreSQL DEFAULT uuid_generate_v7()
    // ---------------------------------------------------------------------------
    public Guid Id { get; private set; }

    // ---------------------------------------------------------------------------
    // Core identity columns
    // ---------------------------------------------------------------------------

    /// <summary>Registered legal name (Arabic or English). VARCHAR(255) NOT NULL.</summary>
    public string LegalName { get; private set; } = string.Empty;

    /// <summary>Trading/display name shown in UI. VARCHAR(255) NOT NULL.</summary>
    public string DisplayName { get; private set; } = string.Empty;

    /// <summary>
    /// رقم السجل التجاري — nullable to support unregistered individual owners.
    /// VARCHAR(50) NULL.
    /// Partial unique constraint: uq_companies_commercial_registration_no
    /// WHERE commercial_registration_no IS NOT NULL.
    /// </summary>
    public string? CommercialRegistrationNo { get; private set; }

    /// <summary>الرقم الضريبي — nullable. VARCHAR(50) NULL.</summary>
    public string? TaxNumber { get; private set; }

    /// <summary>
    /// Company classification. company_type_enum NOT NULL DEFAULT 'individual_owner'.
    /// Approved values: IndividualOwner, PropertyManagementCompany, InvestmentCompany.
    /// </summary>
    public CompanyType CompanyType { get; private set; } = CompanyType.IndividualOwner;

    /// <summary>+962-format validated Jordanian mobile/landline. VARCHAR(20) NOT NULL.</summary>
    public string PrimaryPhone { get; private set; } = string.Empty;

    /// <summary>Nullable — phone-first onboarding is common in this market. VARCHAR(255) NULL.</summary>
    public string? PrimaryEmail { get; private set; }

    /// <summary>ISO 3166-1 alpha-2. CHAR(2) NOT NULL DEFAULT 'JO'.</summary>
    public string CountryCode { get; private set; } = "JO";

    /// <summary>Platform-level kill switch independent of subscription status. BOOLEAN NOT NULL DEFAULT true.</summary>
    public bool IsActive { get; private set; } = true;

    // ---------------------------------------------------------------------------
    // Audit columns — TIMESTAMPTZ / UUID per Global Conventions
    // ---------------------------------------------------------------------------

    public DateTimeOffset CreatedAt { get; private set; }
    public DateTimeOffset UpdatedAt { get; private set; }

    /// <summary>Nullable — system/job-generated rows have no human actor. UUID NULL REFERENCES users(id).</summary>
    public Guid? CreatedBy { get; private set; }

    /// <summary>Nullable — same rationale as CreatedBy. UUID NULL REFERENCES users(id).</summary>
    public Guid? UpdatedBy { get; private set; }

    // ---------------------------------------------------------------------------
    // Soft-delete columns (ISoftDeletable)
    // ---------------------------------------------------------------------------

    /// <summary>TIMESTAMPTZ NULL — NULL means active.</summary>
    public DateTimeOffset? DeletedAt { get; private set; }

    /// <summary>UUID NULL REFERENCES users(id).</summary>
    public Guid? DeletedBy { get; private set; }

    // ---------------------------------------------------------------------------
    // Navigation property — 1:1 to CompanySettings
    // ---------------------------------------------------------------------------

    /// <summary>
    /// One-to-one settings extension. Never null once the company is correctly
    /// onboarded (auto-created in the same application transaction as Company creation).
    /// The physical FK is company_settings.company_id ON DELETE CASCADE.
    /// </summary>
    public CompanySettings? Settings { get; private set; }

    // ---------------------------------------------------------------------------
    // EF Core requires a parameterless constructor (private to prevent misuse).
    // ---------------------------------------------------------------------------
    private Company() { }

    // ---------------------------------------------------------------------------
    // Factory method — enforces only the invariants the approved documents define.
    // UUID is NOT generated here; EF Core reads it back via RETURNING after the
    // database DEFAULT uuid_generate_v7() fires (ValueGeneratedOnAdd strategy).
    // ---------------------------------------------------------------------------

    /// <summary>
    /// Creates a new Company entity with the minimum required fields.
    /// The <paramref name="createdAt"/> value must be UTC-based (DateTimeOffset).
    /// </summary>
    public static Company Create(
        string legalName,
        string displayName,
        string primaryPhone,
        CompanyType companyType,
        string countryCode,
        DateTimeOffset createdAt,
        Guid? createdBy,
        string? commercialRegistrationNo = null,
        string? taxNumber = null,
        string? primaryEmail = null)
    {
        // Approved business invariant: legal_name and display_name must be non-empty.
        // primary_phone must be non-empty (format validated at app/DB CHECK level).
        // country_code must be exactly 2 chars (CHAR(2) DB constraint is authoritative).
        // These guards mirror the NOT NULL / format constraints without duplicating
        // the DB's regex CHECK in C# logic.
        if (string.IsNullOrWhiteSpace(legalName))
            throw new ArgumentException("Legal name is required.", nameof(legalName));
        if (string.IsNullOrWhiteSpace(displayName))
            throw new ArgumentException("Display name is required.", nameof(displayName));
        if (string.IsNullOrWhiteSpace(primaryPhone))
            throw new ArgumentException("Primary phone is required.", nameof(primaryPhone));
        if (string.IsNullOrWhiteSpace(countryCode) || countryCode.Length != 2)
            throw new ArgumentException("Country code must be exactly 2 characters (ISO 3166-1 alpha-2).", nameof(countryCode));

        return new Company
        {
            // Id left at Guid.Empty — the database DEFAULT uuid_generate_v7() sets
            // the real value; EF Core reads it back via RETURNING on INSERT.
            Id = Guid.Empty,
            LegalName = legalName.Trim(),
            DisplayName = displayName.Trim(),
            PrimaryPhone = primaryPhone.Trim(),
            CompanyType = companyType,
            CountryCode = countryCode.ToUpperInvariant(),
            CreatedAt = createdAt,
            UpdatedAt = createdAt,
            CreatedBy = createdBy,
            UpdatedBy = createdBy,
            CommercialRegistrationNo = string.IsNullOrWhiteSpace(commercialRegistrationNo)
                ? null
                : commercialRegistrationNo.Trim(),
            TaxNumber = string.IsNullOrWhiteSpace(taxNumber)
                ? null
                : taxNumber.Trim(),
            PrimaryEmail = string.IsNullOrWhiteSpace(primaryEmail)
                ? null
                : primaryEmail.Trim(),
            IsActive = true
        };
    }

    // ---------------------------------------------------------------------------
    // Mutation methods — only for approved business operations
    // ---------------------------------------------------------------------------

    /// <summary>
    /// Soft-deletes the company. The database constraint remains authoritative
    /// for FK cascade rules on child tables.
    /// </summary>
    public void SoftDelete(DateTimeOffset deletedAt, Guid? deletedBy)
    {
        if (DeletedAt.HasValue)
            return; // Already deleted — idempotent.

        DeletedAt = deletedAt;
        DeletedBy = deletedBy;
        UpdatedAt = deletedAt;
        UpdatedBy = deletedBy;
        IsActive = false;
    }

    /// <summary>Attaches a Settings instance (used by Infrastructure during hydration).</summary>
    internal void SetSettings(CompanySettings settings)
    {
        Settings = settings;
    }
}
