import React, { useState } from "react";
import { useNavigate, useParams } from "react-router";
import { ArrowLeft, Pencil, RefreshCw, Unlink, Receipt, Building2, User, FileText } from "lucide-react";
import { PageContainer } from "@/shared/components/layout/PageContainer";
import { Button } from "@/app/components/ui/button";
import { ConfirmDialog } from "@/shared/components/ui/Overlays";
import { EmptyState, ErrorState, Skeleton } from "@/shared/components/ui/Feedback";
import { useTranslation } from "@/shared/i18n";
import { useRequestUtilitySync, useUnlinkUtilityAccount, useUtilityAccount, useUtilityAccountBills } from "../hooks/useUtilityBills";
import { PaymentBadge, ProviderBadge, SyncBadge } from "../components/UtilityBadges";
import type { UtilityBillPaymentStatus } from "../types/utilityBills.types";
import { providerAvailabilityName, syncStatusName, utilityTypeName } from "../utils/utilityDisplay";
import { extractUserFriendlyError } from "@/shared/utils";
import { toast } from "sonner";
import { ROUTES } from "@/config/routes";
import { ReplaceUtilityAccountModal } from "../components/ReplaceUtilityAccountModal";

export function UtilityAccountDetailsPage() {
  const { id } = useParams(); const navigate = useNavigate(); const { language, formatDate, formatCurrency } = useTranslation(); const ar = language === "ar";
  const [status, setStatus] = useState<UtilityBillPaymentStatus | undefined>(); const [confirmUnlink, setConfirmUnlink] = useState(false); const [editOpen, setEditOpen] = useState(false);
  const account = useUtilityAccount(id); const billsQuery = useUtilityAccountBills(id, status); const bills = billsQuery.data?.pages.flatMap(x => x.items) ?? []; const sync = useRequestUtilitySync(); const unlink = useUnlinkUtilityAccount();
  const syncNow = async () => { if (!id) return; try { await sync.mutateAsync(id); toast.success(ar ? "تم قبول طلب المزامنة." : "Sync request accepted."); } catch(e) { toast.error(extractUserFriendlyError(e, ar?"تعذر طلب المزامنة.":"Unable to request sync.")); } };
  const unlinkNow = async () => { if (!id) return; try { await unlink.mutateAsync(id); toast.success(ar?"تم إلغاء ربط الحساب مع الاحتفاظ بسجل الفواتير.":"Account unlinked; bill history was preserved."); navigate(ROUTES.utilityBills.root); } catch(e) { toast.error(extractUserFriendlyError(e, ar?"تعذر إلغاء الربط.":"Unable to unlink account.")); } };
  if (account.isLoading) return <PageContainer title={ar?"تفاصيل حساب الخدمات":"Utility account details"}><div className="space-y-4">{[1,2,3].map(x=><Skeleton key={x} className="h-28 w-full"/>)}</div></PageContainer>;
  if (account.isError || !account.data) return <PageContainer title={ar?"تفاصيل حساب الخدمات":"Utility account details"}><ErrorState message={ar?"تعذر تحميل الحساب.":"Unable to load this account."} onRetry={() => account.refetch()}/></PageContainer>;
  const a = account.data; const field="h-9 rounded-lg border border-border bg-card px-3 text-xs";
  const canSync = a.isActive && providerAvailabilityName(a.providerAvailability) === "Configured" && syncStatusName(a.syncStatus) !== "Syncing";
  return <PageContainer title={`${utilityTypeName(a.utilityType)==="Water"?(ar?"المياه":"Water"):(ar?"الكهرباء":"Electricity")} · ${a.accountNumber}`} description={ar?"تفاصيل الربط وحالة المزوّد وسجل الفواتير.":"Linkage, provider status, synchronization, and bill history."}>
    <div className="space-y-5">
      <div className="flex flex-wrap justify-between gap-2"><Button variant="ghost" size="sm" onClick={() => navigate(ROUTES.utilityBills.root)} className="gap-1.5"><ArrowLeft className="w-4 h-4 rtl:rotate-180"/>{ar?"العودة":"Back"}</Button><div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" disabled={!a.isActive} onClick={() => setEditOpen(true)}><Pencil className="w-4 h-4"/>{ar?"تعديل":"Edit"}</Button><Button variant="outline" size="sm" disabled={sync.isPending || !canSync} onClick={syncNow} className="gap-1.5"><RefreshCw className={`w-4 h-4 ${sync.isPending?"animate-spin":""}`}/>{ar?"طلب المزامنة":"Request sync"}</Button><Button variant="destructive" size="sm" disabled={unlink.isPending || !a.isActive || syncStatusName(a.syncStatus) === "Syncing"} onClick={() => setConfirmUnlink(true)} className="gap-1.5"><Unlink className="w-4 h-4"/>{ar?"إلغاء الربط":"Unlink"}</Button></div></div>
      {providerAvailabilityName(a.providerAvailability) !== "Configured" && <div className="rounded-xl border border-warning/40 bg-warning-bg p-4 text-xs"><p className="font-semibold">{ar?"المزامنة التلقائية غير متاحة حالياً.":"Automatic synchronization is currently unavailable."}</p><p className="text-muted-foreground mt-1">{ar?"حالة إعداد المزوّد موضحة أدناه؛ بيانات الحساب والفواتير المحفوظة ما زالت متاحة.":"The provider configuration state is shown below; saved account and bill data remains available."}</p></div>}
      <div className="rounded-xl border border-border bg-card p-5 grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 text-xs"><Info icon={User} label={ar?"المستأجر":"Tenant"} value={a.tenantName}/><Info icon={Building2} label={ar?"العقار والوحدة":"Property & unit"} value={`${a.buildingName} · ${a.unitNumber}`}/><Info icon={FileText} label={ar?"عقد الإيجار":"Lease contract"} value={a.leaseContractNumber}/><Info icon={Receipt} label={ar?"رقم العداد":"Meter number"} value={a.meterNumber || "—"}/><div><p className="text-muted-foreground mb-1.5">{ar?"حالة المزامنة":"Sync status"}</p><SyncBadge value={a.syncStatus}/></div><div><p className="text-muted-foreground mb-1.5">{ar?"حالة المزوّد":"Provider availability"}</p><ProviderBadge value={a.providerAvailability}/></div><Info label={ar?"آخر مزامنة ناجحة":"Last successful sync"} value={a.lastSuccessfulSyncAt?formatDate(a.lastSuccessfulSyncAt,language):"—"}/><Info label={ar?"محاولات الفشل المتتالية":"Consecutive failures"} value={String(a.consecutiveFailureCount)}/></div>
      <div className="space-y-3"><div className="flex items-center justify-between gap-3"><h2 className="font-semibold text-sm">{ar?"سجل الفواتير":"Bill history"}</h2><select className={field} value={status === undefined?"":String(status)} onChange={e=>setStatus((e.target.value||undefined) as UtilityBillPaymentStatus|undefined)}><option value="">{ar?"كل حالات الدفع":"All payment statuses"}</option><option value="Paid">{ar?"مدفوعة":"Paid"}</option><option value="Unpaid">{ar?"غير مدفوعة":"Unpaid"}</option><option value="Unknown">{ar?"غير معروف":"Unknown"}</option></select></div>
        {billsQuery.isLoading?<div className="space-y-3">{[1,2,3].map(x=><Skeleton key={x} className="h-12 w-full"/>)}</div>:billsQuery.isError?<ErrorState message={ar?"تعذر تحميل سجل الفواتير.":"Unable to load bill history."} onRetry={()=>billsQuery.refetch()}/>:bills.length===0?<EmptyState icon={Receipt} title={ar?"لا توجد فواتير":"No bills found"} description={ar?"لا توجد فواتير مطابقة لحالة الدفع المحددة.":"No bills match the selected payment status."}/>:<><div className="hidden md:block rounded-xl border border-border bg-card overflow-x-auto"><table className="w-full text-xs"><thead className="bg-secondary/50 text-muted-foreground"><tr><th className="p-3 text-start">{ar?"تاريخ الفاتورة":"Bill date"}</th><th className="p-3 text-start">{ar?"الاستحقاق":"Due date"}</th><th className="p-3 text-start">{ar?"المبلغ":"Amount"}</th><th className="p-3 text-start">{ar?"الدفع":"Payment"}</th><th className="p-3 text-start">{ar?"تاريخ الاكتشاف":"Discovered"}</th></tr></thead><tbody className="divide-y divide-border">{bills.map(b=><tr key={b.id}><td className="p-3">{formatDate(b.billDate,language)}</td><td className="p-3">{b.dueDate?formatDate(b.dueDate,language):"—"}</td><td className="p-3 font-mono font-semibold">{formatCurrency(b.amount,{currency:b.currency})}</td><td className="p-3"><PaymentBadge value={b.paymentStatus}/></td><td className="p-3 text-muted-foreground">{formatDate(b.discoveredAt,language)}</td></tr>)}</tbody></table></div><div className="md:hidden space-y-3">{bills.map(b=><article key={b.id} className="rounded-xl border border-border bg-card p-4 text-xs space-y-2"><div className="flex items-center justify-between gap-3"><p className="font-mono font-bold text-sm">{formatCurrency(b.amount,{currency:b.currency})}</p><PaymentBadge value={b.paymentStatus}/></div><div className="grid grid-cols-2 gap-2 text-muted-foreground"><p>{ar?"الفاتورة":"Bill"}: <span className="text-foreground">{formatDate(b.billDate,language)}</span></p><p>{ar?"الاستحقاق":"Due"}: <span className="text-foreground">{b.dueDate?formatDate(b.dueDate,language):"—"}</span></p></div><p className="text-muted-foreground">{ar?"اكتُشفت":"Discovered"}: {formatDate(b.discoveredAt,language)}</p></article>)}</div>{billsQuery.hasNextPage&&<div className="flex justify-center"><Button variant="outline" size="sm" disabled={billsQuery.isFetchingNextPage} onClick={()=>billsQuery.fetchNextPage()}>{billsQuery.isFetchingNextPage?(ar?"جارٍ التحميل...":"Loading..."):(ar?"تحميل المزيد":"Load more")}</Button></div>}</>}
      </div>
    </div><ReplaceUtilityAccountModal account={editOpen ? a : null} onClose={() => setEditOpen(false)} /><ConfirmDialog isOpen={confirmUnlink} onClose={()=>setConfirmUnlink(false)} onConfirm={unlinkNow} isLoading={unlink.isPending} title={ar?"إلغاء ربط حساب الخدمات؟":"Unlink utility account?"} description={ar?"سيتم إيقاف المزامنة المستقبلية مع الاحتفاظ بسجل الفواتير لأغراض التدقيق.":"Future synchronization will stop. Existing bill history is preserved for audit."} confirmLabel={ar?"إلغاء الربط":"Unlink"}/>
  </PageContainer>;
}
function Info({ icon: Icon, label, value }: { icon?: React.ComponentType<{className?:string}>; label:string; value:string }) { return <div className="min-w-0">{Icon&&<Icon className="w-4 h-4 text-primary mb-1.5"/>}<p className="text-muted-foreground">{label}</p><p className="font-semibold mt-1 truncate" title={value}>{value}</p></div>; }
