using PropertyOS.Domain.Common;
using PropertyOS.Domain.Properties.Enums;

namespace PropertyOS.Domain.Properties;

/// <summary>
/// Represents a physical building owned/managed by a company.
/// Maps to the PostgreSQL table: <c>buildings</c> (Module 4 §4.1).
///
/// Hierarchy root: Company → Building → Floor → Apartment.
///
/// <b>Denormalized fields:</b>
///   <c>total_apartments_count</c> is a trigger-maintained cache updated by an
///   AFTER INSERT OR UPDATE OF deleted_at ON apartments trigger. Application code
///   must NOT maintain this counter; the trigger is the sole owner.
///
/// Soft-delete: YES (standard deleted_at / deleted_by).
/// RLS: ENABLE + FORCE on the table; policy scopes by company_id via app.current_company_id.
/// </summary>
public class Building : ISoftDeletable
{
    // ---------------------------------------------------------------------------
    // Primary Key — UUID v7 generated by PostgreSQL DEFAULT uuid_generate_v7()
    // ---------------------------------------------------------------------------
    public Guid Id { get; private set; }

    // ---------------------------------------------------------------------------
    // Tenant key — denormalized onto this table for RLS and hot-path indexing.
    // ---------------------------------------------------------------------------

    /// <summary>UUID NOT NULL REFERENCES companies(id) ON DELETE RESTRICT.</summary>
    public Guid CompanyId { get; private set; }

    // ---------------------------------------------------------------------------
    // Core identity columns
    // ---------------------------------------------------------------------------

    /// <summary>Building name/label. VARCHAR(255) NOT NULL.</summary>
    public string Name { get; private set; } = string.Empty;

    /// <summary>Optional company-internal reference code. VARCHAR(50) NULL.</summary>
    public string? InternalCode { get; private set; }

    /// <summary>Building classification. building_type_enum NOT NULL DEFAULT 'residential'.</summary>
    public BuildingType BuildingType { get; private set; } = BuildingType.Residential;

    /// <summary>
    /// Declared floor count from the municipal permit. SMALLINT NOT NULL.
    /// Not required to equal COUNT(floors) — see Module 4 §4.1 Business Rules.
    /// DB CHECK: total_floors > 0.
    /// </summary>
    public short TotalFloors { get; private set; }

    /// <summary>SMALLINT NULL.</summary>
    public short? ConstructionYear { get; private set; }

    /// <summary>NUMERIC(10,7) NULL. Both GPS columns must be NULL or both NOT NULL (chk_buildings_gps_pair).</summary>
    public decimal? GpsLatitude { get; private set; }

    /// <summary>NUMERIC(10,7) NULL.</summary>
    public decimal? GpsLongitude { get; private set; }

    /// <summary>
    /// Denormalized apartment counter. INTEGER NOT NULL DEFAULT 0.
    /// Maintained exclusively by the PostgreSQL trigger defined in the migration.
    /// Application code must NOT write this property directly.
    /// </summary>
    public int TotalApartmentsCount { get; private set; } = 0;

    /// <summary>Operationally active flag. BOOLEAN NOT NULL DEFAULT true.</summary>
    public bool IsActive { get; private set; } = true;

    // ---------------------------------------------------------------------------
    // Audit columns
    // ---------------------------------------------------------------------------

    public DateTimeOffset CreatedAt { get; private set; }
    public DateTimeOffset UpdatedAt { get; private set; }

    /// <summary>UUID NULL REFERENCES users(id) ON DELETE SET NULL.</summary>
    public Guid? CreatedBy { get; private set; }

    /// <summary>UUID NULL REFERENCES users(id) ON DELETE SET NULL.</summary>
    public Guid? UpdatedBy { get; private set; }

    // ---------------------------------------------------------------------------
    // Soft-delete columns (ISoftDeletable)
    // ---------------------------------------------------------------------------

    /// <summary>TIMESTAMPTZ NULL — NULL means active.</summary>
    public DateTimeOffset? DeletedAt { get; private set; }

    /// <summary>UUID NULL REFERENCES users(id) ON DELETE SET NULL.</summary>
    public Guid? DeletedBy { get; private set; }

    // ---------------------------------------------------------------------------
    // Navigation properties
    // ---------------------------------------------------------------------------

    /// <summary>1:1 address extension. Never null once correctly onboarded.</summary>
    public BuildingAddress? Address { get; private set; }

    /// <summary>Floors belonging to this building.</summary>
    public IReadOnlyCollection<Floor> Floors => _floors.AsReadOnly();
    private readonly List<Floor> _floors = new();

    // ---------------------------------------------------------------------------
    // EF Core requires a parameterless constructor (private to prevent misuse).
    // ---------------------------------------------------------------------------
    private Building() { }

    // ---------------------------------------------------------------------------
    // Factory method
    // ---------------------------------------------------------------------------

    /// <summary>
    /// Creates a new Building entity with the minimum required fields.
    /// <paramref name="totalFloors"/> must be positive (DB CHECK authoritative).
    /// <paramref name="gpsLatitude"/> and <paramref name="gpsLongitude"/> must
    /// both be provided or both null (DB CHECK authoritative).
    /// </summary>
    public static Building Create(
        Guid companyId,
        string name,
        short totalFloors,
        DateTimeOffset createdAt,
        Guid? createdBy,
        BuildingType buildingType = BuildingType.Residential,
        string? internalCode = null,
        short? constructionYear = null,
        decimal? gpsLatitude = null,
        decimal? gpsLongitude = null)
    {
        if (companyId == Guid.Empty)
            throw new ArgumentException("CompanyId must be a valid non-empty Guid.", nameof(companyId));
        if (string.IsNullOrWhiteSpace(name))
            throw new ArgumentException("Building name is required.", nameof(name));
        if (totalFloors <= 0)
            throw new ArgumentOutOfRangeException(nameof(totalFloors), "Total floors must be positive.");

        // Both GPS coordinates or neither — mirrors DB chk_buildings_gps_pair.
        bool latIsNull = gpsLatitude is null;
        bool lonIsNull = gpsLongitude is null;
        if (latIsNull != lonIsNull)
            throw new ArgumentException(
                "gps_latitude and gps_longitude must both be provided or both null.",
                nameof(gpsLatitude));

        return new Building
        {
            Id = Guid.Empty,
            CompanyId = companyId,
            Name = name.Trim(),
            InternalCode = string.IsNullOrWhiteSpace(internalCode) ? null : internalCode.Trim(),
            BuildingType = buildingType,
            TotalFloors = totalFloors,
            ConstructionYear = constructionYear,
            GpsLatitude = gpsLatitude,
            GpsLongitude = gpsLongitude,
            TotalApartmentsCount = 0,
            IsActive = true,
            CreatedAt = createdAt,
            UpdatedAt = createdAt,
            CreatedBy = createdBy,
            UpdatedBy = createdBy,
        };
    }

    // ---------------------------------------------------------------------------
    // Mutation methods
    // ---------------------------------------------------------------------------

    /// <summary>Deactivates the building (keeps it soft-visible for historical queries).</summary>
    public void Deactivate(DateTimeOffset updatedAt, Guid? updatedBy)
    {
        IsActive = false;
        UpdatedAt = updatedAt;
        UpdatedBy = updatedBy;
    }

    /// <summary>Standard soft-delete. All child floors/apartments/history remain intact.</summary>
    public void SoftDelete(DateTimeOffset deletedAt, Guid? deletedBy)
    {
        if (DeletedAt.HasValue) return; // Idempotent.
        DeletedAt = deletedAt;
        DeletedBy = deletedBy;
        IsActive = false;
        UpdatedAt = deletedAt;
        UpdatedBy = deletedBy;
    }

    /// <summary>Attaches address (used by infrastructure layer during hydration).</summary>
    internal void SetAddress(BuildingAddress address)
    {
        Address = address;
    }
}
