// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PropertyOS.Infrastructure.Persistence;

#nullable disable

namespace PropertyOS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PropertyOsDbContext))]
    [Migration("20260703173554_Module2_Plans_Subscriptions_Foundation")]
    partial class Module2_Plans_Subscriptions_Foundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "billing_cycle_enum", "billing_cycle_enum", new[] { "monthly", "yearly" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "company_type_enum", "company_type", new[] { "individual_owner", "property_management_company", "investment_company" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "late_fee_type_enum", "late_fee_type", new[] { "none", "fixed", "percentage" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "subscription_status_enum", "subscription_status_enum", new[] { "trialing", "active", "past_due", "suspended", "cancelled", "expired" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PropertyOS.Domain.Companies.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v7()");

                    b.Property<string>("CommercialRegistrationNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("commercial_registration_no");

                    b.Property<int>("CompanyType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("company_type_enum")
                        .HasDefaultValue(0)
                        .HasColumnName("company_type");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasDefaultValue("JO")
                        .HasColumnName("country_code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("legal_name");

                    b.Property<string>("PrimaryEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("primary_email");

                    b.Property<string>("PrimaryPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("primary_phone");

                    b.Property<string>("TaxNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tax_number");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CommercialRegistrationNo")
                        .IsUnique()
                        .HasDatabaseName("uq_companies_commercial_registration_no");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("idx_companies_deleted_at");

                    b.ToTable("companies", null, t =>
                        {
                            t.HasCheckConstraint("chk_companies_primary_phone_format", "primary_phone ~ '^\\+962[0-9]{8,9}$'");
                        });
                });

            modelBuilder.Entity("PropertyOS.Domain.Companies.CompanySettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v7()");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DefaultCurrency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasDefaultValue("JOD")
                        .HasColumnName("default_currency");

                    b.Property<string>("DefaultLanguage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasDefaultValue("ar")
                        .HasColumnName("default_language");

                    b.Property<short>("FiscalYearStartMonth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("fiscal_year_start_month");

                    b.Property<int>("LateFeeType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("late_fee_type_enum")
                        .HasDefaultValue(0)
                        .HasColumnName("late_fee_type");

                    b.Property<decimal?>("LateFeeValue")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("late_fee_value");

                    b.Property<short>("RentGracePeriodDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)5)
                        .HasColumnName("rent_grace_period_days");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Asia/Amman")
                        .HasColumnName("timezone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique()
                        .HasDatabaseName("uq_company_settings_company_id");

                    b.ToTable("company_settings", null, t =>
                        {
                            t.HasCheckConstraint("chk_company_settings_fiscal_month", "fiscal_year_start_month BETWEEN 1 AND 12");

                            t.HasCheckConstraint("chk_company_settings_late_fee_value", "(late_fee_type = 'none' AND late_fee_value IS NULL) OR (late_fee_type != 'none' AND late_fee_value IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("PropertyOS.Domain.Subscriptions.CompanySubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v7()");

                    b.Property<bool>("AutoRenew")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("auto_renew");

                    b.Property<int>("BillingCycle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("billing_cycle_enum")
                        .HasColumnName("billing_cycle")
                        .HasDefaultValueSql("'monthly'::billing_cycle_enum");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CurrencyAtSubscription")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(3)")
                        .HasDefaultValue("JOD")
                        .HasColumnName("currency_at_subscription");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<DateTimeOffset?>("ExpiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_at");

                    b.Property<string>("ExternalBillingRef")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("external_billing_ref");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<decimal>("PriceAtSubscription")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("price_at_subscription");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("subscription_status_enum")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'trialing'::subscription_status_enum");

                    b.Property<DateTimeOffset?>("SuspendedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("suspended_at");

                    b.Property<string>("SuspensionReason")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("suspension_reason");

                    b.Property<DateOnly?>("TrialEndDate")
                        .HasColumnType("date")
                        .HasColumnName("trial_end_date");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique()
                        .HasDatabaseName("uq_company_subscriptions_one_active")
                        .HasFilter("status IN ('trialing','active','past_due')");

                    b.HasIndex("EndDate")
                        .HasDatabaseName("idx_company_subscriptions_end_date")
                        .HasFilter("status IN ('trialing','active','past_due')");

                    b.HasIndex("PlanId");

                    b.HasIndex("CompanyId", "Status")
                        .HasDatabaseName("idx_company_subscriptions_company_status");

                    b.ToTable("company_subscriptions", null, t =>
                        {
                            t.HasCheckConstraint("chk_company_subscriptions_dates", "end_date > start_date");

                            t.HasCheckConstraint("chk_company_subscriptions_suspension", "suspension_reason IS NOT NULL OR suspended_at IS NULL");

                            t.HasCheckConstraint("chk_company_subscriptions_trial_end", "trial_end_date IS NOT NULL OR status != 'trialing'");
                        });
                });

            modelBuilder.Entity("PropertyOS.Domain.Subscriptions.SubscriptionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v7()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(3)")
                        .HasDefaultValue("JOD")
                        .HasColumnName("currency");

                    b.Property<string>("DescriptionAr")
                        .HasColumnType("text")
                        .HasColumnName("description_ar");

                    b.Property<string>("DescriptionEn")
                        .HasColumnType("text")
                        .HasColumnName("description_en");

                    b.Property<string>("FeatureFlags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("feature_flags");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int?>("MaxBuildings")
                        .HasColumnType("integer")
                        .HasColumnName("max_buildings");

                    b.Property<int?>("MaxStorageMb")
                        .HasColumnType("integer")
                        .HasColumnName("max_storage_mb");

                    b.Property<int?>("MaxUsers")
                        .HasColumnType("integer")
                        .HasColumnName("max_users");

                    b.Property<decimal>("MonthlyPrice")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("monthly_price");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name_en");

                    b.Property<short>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("sort_order");

                    b.Property<bool>("SupportsTrial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("supports_trial");

                    b.Property<short?>("TrialDurationDays")
                        .HasColumnType("smallint")
                        .HasColumnName("trial_duration_days");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("YearlyPrice")
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("yearly_price");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_subscription_plans_code");

                    b.HasIndex("IsActive", "SortOrder")
                        .HasDatabaseName("idx_subscription_plans_active_sort")
                        .HasFilter("is_active = true");

                    b.ToTable("subscription_plans", null, t =>
                        {
                            t.HasCheckConstraint("chk_subscription_plans_prices_positive", "monthly_price > 0 AND yearly_price > 0");

                            t.HasCheckConstraint("chk_subscription_plans_quotas_positive", "(max_buildings IS NULL OR max_buildings > 0) AND (max_users IS NULL OR max_users > 0) AND (max_storage_mb IS NULL OR max_storage_mb > 0)");

                            t.HasCheckConstraint("chk_subscription_plans_trial_duration", "trial_duration_days IS NOT NULL OR supports_trial = false");
                        });
                });

            modelBuilder.Entity("PropertyOS.Domain.Companies.CompanySettings", b =>
                {
                    b.HasOne("PropertyOS.Domain.Companies.Company", "Company")
                        .WithOne("Settings")
                        .HasForeignKey("PropertyOS.Domain.Companies.CompanySettings", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("PropertyOS.Domain.Subscriptions.CompanySubscription", b =>
                {
                    b.HasOne("PropertyOS.Domain.Companies.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PropertyOS.Domain.Subscriptions.SubscriptionPlan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("PropertyOS.Domain.Companies.Company", b =>
                {
                    b.Navigation("Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
