import { useMemo, useState } from "react";
import { toast } from "sonner";
import { Button } from "@/shared/ui/button";
import { Input } from "@/shared/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/shared/ui/select";
import { Skeleton } from "@/shared/ui/skeleton";
import { ErrorState } from "@/shared/components/ui/Feedback";
import { useTranslation } from "@/shared/i18n";
import { useAuth } from "@/features/auth/hooks/useAuth";
import { useAvailablePlans, useCancelMyPlanChangeRequest, useCreateMyPlanChangeRequest, useMyPlanChangeRequests, useMySubscription } from "../hooks/useSubscriptions";
import type { BillingCycle, PlanChangeRequestDto, SubscriptionPlanDto } from "../types/subscriptions.types";
import { DetailsDrawer, DetailList, SubscriptionStatusBadge } from "../components/SubscriptionPrimitives";
import { getSubscriptionError } from "../utils/subscriptionErrors";

const PAGE_SIZE = 20;
const message = getSubscriptionError;

export function CompanySubscriptionsPage() {
  const { t, language, formatCurrency, formatDate } = useTranslation();
  const { user } = useAuth();
  const [requestPage, setRequestPage] = useState(1); const [selectedPlan, setSelectedPlan] = useState<SubscriptionPlanDto | null>(null); const [cycle, setCycle] = useState<BillingCycle>("Monthly"); const [requestDrawer, setRequestDrawer] = useState<PlanChangeRequestDto | null>(null);
  const subscription = useMySubscription(); const plans = useAvailablePlans(1, 100); const requests = useMyPlanChangeRequests(requestPage, PAGE_SIZE); const create = useCreateMyPlanChangeRequest(); const cancel = useCancelMyPlanChangeRequest();
  const canView = user?.permissions?.includes("subscriptions.own.read") === true; const canRequest = user?.permissions?.includes("subscriptions.plan_change_requests.own.create") === true; const canCancel = user?.permissions?.includes("subscriptions.plan_change_requests.own.cancel") === true;
  const current = subscription.data; const selectedPrice = selectedPlan && (cycle === "Yearly" ? selectedPlan.yearlyPrice : selectedPlan.monthlyPrice);
  const totalPages = Math.max(1, Math.ceil((requests.data?.totalCount ?? 0) / PAGE_SIZE));
  const unavailablePlanIds = useMemo(() => new Set(current ? [current.planId] : []), [current]);
  if (!canView) return <ErrorState title={t("subscriptions.errors.forbidden")} />;
  const submit = async () => { if (!selectedPlan || create.isPending) return; try { await create.mutateAsync({ requestedPlanId: selectedPlan.id, requestedBillingCycle: cycle }); toast.success(t("subscriptions.requestCreated")); setSelectedPlan(null); } catch (error) { toast.error(message(error, t)); } };
  const cancelRequest = async (id: string) => { try { await cancel.mutateAsync(id); toast.success(t("subscriptions.requestCancelled")); setRequestDrawer(null); } catch (error) { toast.error(message(error, t)); } };
  return <section className="space-y-8">
    <header><h1 className="text-xl font-bold tracking-tight">{t("subscriptions.title")}</h1></header>
    <section className="rounded-lg border border-border bg-card p-5">
      <h2 className="text-sm font-semibold">{t("subscriptions.current")}</h2>
      {subscription.isLoading && <Skeleton className="mt-4 h-20 w-full" />}
      {subscription.isError && <ErrorState title={message(subscription.error, t)} onRetry={() => subscription.refetch()} />}
      {!subscription.isLoading && !subscription.isError && !current && <p className="mt-4 text-sm text-muted-foreground">{t("subscriptions.noSubscription")}</p>}
      {current && <div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div><p className="text-xs text-muted-foreground">{t("subscriptions.plan")}</p><p className="font-medium">{language === "ar" ? current.planNameAr : current.planNameEn}</p></div><div><p className="text-xs text-muted-foreground">{t("common.status")}</p><SubscriptionStatusBadge value={current.status} /></div><div><p className="text-xs text-muted-foreground">{t("subscriptions.price")}</p><p className="font-medium">{formatCurrency(current.priceAtSubscription, { currency: current.currencyAtSubscription })} / {t(`subscriptions.${current.billingCycle.toLowerCase()}`)}</p></div><div><p className="text-xs text-muted-foreground">{t("subscriptions.endDate")}</p><p className="font-medium">{formatDate(current.endDate, { dateStyle: "medium" })}</p></div></div>}
    </section>
    <section className="space-y-3"><div><h2 className="text-sm font-semibold">{t("subscriptions.availablePlans")}</h2><p className="mt-1 text-xs text-muted-foreground">{t("subscriptions.requestNotice")}</p></div>
      {plans.isLoading && <Skeleton className="h-28 w-full" />}{plans.isError && <ErrorState title={message(plans.error, t)} onRetry={() => plans.refetch()} />}
      {plans.data?.items.length === 0 && <p className="text-sm text-muted-foreground">{t("subscriptions.noPlans")}</p>}
      <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{plans.data?.items.map((plan) => { const isCurrent = unavailablePlanIds.has(plan.id); return <div key={plan.id} className="rounded-lg border border-border bg-card p-4"><p className="font-medium">{language === "ar" ? plan.nameAr : plan.nameEn}</p><div className="mt-3 space-y-1 text-sm"><p>{formatCurrency(plan.monthlyPrice, { currency: plan.currency })} / {t("subscriptions.monthly")}</p><p>{formatCurrency(plan.yearlyPrice, { currency: plan.currency })} / {t("subscriptions.yearly")}</p></div><div className="mt-3 grid grid-cols-2 gap-2 text-xs text-muted-foreground"><p>{t("subscriptions.planForm.buildings")}: <span className="text-foreground">{plan.maxBuildings ?? t("subscriptions.planForm.unlimited")}</span></p><p>{t("subscriptions.planForm.users")}: <span className="text-foreground">{plan.maxUsers ?? t("subscriptions.planForm.unlimited")}</span></p>{plan.supportsTrial && <p className="col-span-2">{t("subscriptions.planForm.trial")}: <span className="text-foreground">{plan.trialDurationDays} {t("subscriptions.planForm.days")}</span></p>}</div><Button className="mt-4 w-full" size="sm" variant={isCurrent ? "outline" : "default"} disabled={isCurrent || !canRequest} onClick={() => { setSelectedPlan(plan); setCycle("Monthly"); }}>{isCurrent ? t("subscriptions.currentPlan") : t("subscriptions.requestChange")}</Button></div>; })}</div>
    </section>
    <section className="space-y-3"><h2 className="text-sm font-semibold">{t("subscriptions.requests")}</h2>{requests.isLoading && <Skeleton className="h-20 w-full" />}{requests.isError && <div className="flex flex-wrap items-center justify-between gap-3 rounded-md border border-destructive/30 px-4 py-3 text-sm"><span className="text-destructive">{t("subscriptions.requestsLoadError")}</span><Button variant="outline" size="sm" onClick={() => requests.refetch()}>{t("common.retry")}</Button></div>}{requests.data?.items.length === 0 && <p className="text-sm text-muted-foreground">{t("subscriptions.noRequests")}</p>}{requests.data && requests.data.items.length > 0 && <div className="overflow-hidden rounded-lg border border-border"><table className="w-full text-sm"><thead className="bg-muted/40 text-xs text-muted-foreground"><tr><th className="p-3 text-start">{t("subscriptions.requestedPlan")}</th><th className="p-3 text-start">{t("subscriptions.submitted")}</th><th className="p-3 text-start">{t("common.status")}</th></tr></thead><tbody>{requests.data.items.map((item) => <tr key={item.id} className="cursor-pointer border-t border-border hover:bg-muted/40" onClick={() => setRequestDrawer(item)}><td className="p-3">{language === "ar" ? item.requestedPlanNameAr : item.requestedPlanNameEn}</td><td className="p-3">{formatDate(item.requestedAt, { dateStyle: "medium" })}</td><td className="p-3"><SubscriptionStatusBadge value={item.status} /></td></tr>)}</tbody></table></div>}{totalPages > 1 && <div className="flex justify-end gap-2"><Button variant="outline" size="sm" disabled={requestPage === 1} onClick={() => setRequestPage((p) => p - 1)}>{t("common.back")}</Button><Button variant="outline" size="sm" disabled={requestPage === totalPages} onClick={() => setRequestPage((p) => p + 1)}>{t("common.next")}</Button></div>}</section>
    <DetailsDrawer open={Boolean(selectedPlan)} title={t("subscriptions.requestChange")} onClose={() => setSelectedPlan(null)} footer={<><Button variant="outline" onClick={() => setSelectedPlan(null)}>{t("common.cancel")}</Button><Button disabled={create.isPending} onClick={submit}>{create.isPending ? t("common.processing") : t("common.submit")}</Button></>}><div className="space-y-5"><DetailList items={[{ label: t("subscriptions.plan"), value: selectedPlan && (language === "ar" ? selectedPlan.nameAr : selectedPlan.nameEn) }]} /><div><label className="text-xs text-muted-foreground">{t("subscriptions.billingCycle")}</label><Select value={cycle} onValueChange={(value) => setCycle(value as BillingCycle)}><SelectTrigger className="mt-1"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="Monthly">{t("subscriptions.monthly")}</SelectItem><SelectItem value="Yearly">{t("subscriptions.yearly")}</SelectItem></SelectContent></Select></div>{selectedPlan && <p className="text-sm font-medium">{formatCurrency(selectedPrice!, { currency: selectedPlan.currency })}</p>}<p className="text-sm text-muted-foreground">{t("subscriptions.requestNotice")}</p></div></DetailsDrawer>
    <DetailsDrawer open={Boolean(requestDrawer)} title={t("subscriptions.platformRequests.requestDetails")} onClose={() => setRequestDrawer(null)} footer={requestDrawer?.status === "Pending" && canCancel ? <Button variant="destructive" disabled={cancel.isPending} onClick={() => cancelRequest(requestDrawer.id)}>{t("subscriptions.cancelRequest")}</Button> : undefined}><DetailList items={requestDrawer ? [{ label: t("subscriptions.currentPlan"), value: language === "ar" ? requestDrawer.currentPlanNameAr : requestDrawer.currentPlanNameEn }, { label: t("subscriptions.requestedPlan"), value: language === "ar" ? requestDrawer.requestedPlanNameAr : requestDrawer.requestedPlanNameEn }, { label: t("subscriptions.billingCycle"), value: t(`subscriptions.${requestDrawer.requestedBillingCycle.toLowerCase()}`) }, { label: t("common.status"), value: <SubscriptionStatusBadge value={requestDrawer.status} /> }, { label: t("subscriptions.rejectionReason"), value: requestDrawer.rejectionReason }, { label: t("subscriptions.decisionNote"), value: requestDrawer.decisionNote }] : []} /></DetailsDrawer>
  </section>;
}
